/* inhale/en.h — English heavy vocabulary for brodsky.c
 * 810 words. Latinisms, polysyllables, Brodsky's actual lexicon.
 * Plath (domestic horror, female viscera), Celan (broken language, absence).
 * Each word: text, mass, syllables, emotion, consonant_density (precomputed)
 */

/* W(word, mass, syllables, emotion) */
#define INHALE_EN \
/* === HEAVY ETERNALS === */ \
W("death",           0.95, 1, EMO_TRAUMA), \
W("empire",          0.85, 2, EMO_VOID), \
W("infinity",        0.80, 5, EMO_RESONANCE), \
W("sovereignty",     0.75, 4, EMO_VOID), \
W("eternity",        0.80, 4, EMO_RESONANCE), \
W("consciousness",   0.70, 3, EMO_RESONANCE), \
W("civilization",    0.65, 5, EMO_VOID), \
W("architecture",    0.70, 4, EMO_RESONANCE), \
W("metamorphosis",   0.75, 5, EMO_RESONANCE), \
W("deterioration",   0.70, 6, EMO_TRAUMA), \
/* === BRODSKY LEXICON — from actual poems === */ \
W("province",        0.60, 2, EMO_JULIA), \
W("column",          0.55, 2, EMO_VOID), \
W("portico",         0.60, 3, EMO_VOID), \
W("facade",          0.55, 2, EMO_VOID), \
W("cornice",         0.50, 2, EMO_VOID), \
W("balustrade",      0.60, 3, EMO_VOID), \
W("marble",          0.65, 2, EMO_VOID), \
W("gravel",          0.40, 2, EMO_VOID), \
W("cobblestone",     0.50, 3, EMO_VOID), \
W("estuary",         0.55, 4, EMO_RESONANCE), \
W("quay",            0.45, 1, EMO_JULIA), \
W("pier",            0.40, 1, EMO_JULIA), \
W("longitude",       0.55, 3, EMO_RESONANCE), \
W("latitude",        0.55, 3, EMO_RESONANCE), \
W("meridian",        0.60, 4, EMO_RESONANCE), \
W("hemisphere",      0.60, 3, EMO_VOID), \
W("peninsula",       0.55, 4, EMO_JULIA), \
W("cartography",     0.60, 4, EMO_RESONANCE), \
W("permafrost",      0.65, 3, EMO_VOID), \
W("archipelago",     0.55, 5, EMO_RESONANCE), \
/* === GEOMETRY — Brodsky loved geometry === */ \
W("perpendicular",   0.65, 5, EMO_RESONANCE), \
W("tangent",         0.50, 2, EMO_RESONANCE), \
W("parabola",        0.60, 4, EMO_RESONANCE), \
W("hyperbola",       0.55, 4, EMO_RESONANCE), \
W("asymptote",       0.60, 3, EMO_JULIA), \
W("intersection",    0.55, 4, EMO_RESONANCE), \
W("circumference",   0.60, 4, EMO_RESONANCE), \
W("diagonal",        0.50, 4, EMO_RESONANCE), \
W("parallel",        0.55, 3, EMO_RESONANCE), \
W("trapezoid",       0.50, 3, EMO_RESONANCE), \
W("vector",          0.55, 2, EMO_RESONANCE), \
W("rectangle",       0.45, 3, EMO_RESONANCE), \
W("rhombus",         0.50, 2, EMO_RESONANCE), \
W("hypotenuse",      0.55, 4, EMO_RESONANCE), \
W("ellipsis",        0.50, 3, EMO_RESONANCE), \
W("vertex",          0.50, 2, EMO_RESONANCE), \
W("bisector",        0.50, 3, EMO_RESONANCE), \
W("parallelogram",   0.55, 5, EMO_RESONANCE), \
/* === BODY — grotesque, medical === */ \
W("vertebra",        0.70, 3, EMO_TRAUMA), \
W("cartilage",       0.60, 3, EMO_TRAUMA), \
W("ligament",        0.55, 3, EMO_TRAUMA), \
W("tendon",          0.55, 2, EMO_TRAUMA), \
W("sternum",         0.65, 2, EMO_TRAUMA), \
W("larynx",          0.60, 2, EMO_TRAUMA), \
W("pharynx",         0.55, 2, EMO_TRAUMA), \
W("esophagus",       0.55, 4, EMO_TRAUMA), \
W("abdomen",         0.50, 3, EMO_TRAUMA), \
W("diaphragm",       0.60, 3, EMO_TRAUMA), \
W("collarbone",      0.55, 3, EMO_TRAUMA), \
W("ribcage",         0.60, 2, EMO_TRAUMA), \
W("skull",           0.70, 1, EMO_TRAUMA), \
W("spine",           0.65, 1, EMO_TRAUMA), \
W("clavicle",        0.60, 3, EMO_TRAUMA), \
W("femur",           0.55, 2, EMO_TRAUMA), \
W("patella",         0.55, 3, EMO_TRAUMA), \
W("trachea",         0.60, 3, EMO_TRAUMA), \
W("aorta",           0.65, 3, EMO_TRAUMA), \
W("pelvis",          0.55, 2, EMO_TRAUMA), \
W("sacrum",          0.55, 2, EMO_TRAUMA), \
W("cochlea",         0.50, 3, EMO_TRAUMA), \
W("retina",          0.50, 3, EMO_TRAUMA), \
W("synapse",         0.55, 2, EMO_RESONANCE), \
W("scapula",         0.55, 3, EMO_TRAUMA), \
W("tibia",           0.50, 3, EMO_TRAUMA), \
W("ulna",            0.45, 2, EMO_TRAUMA), \
W("cranium",         0.60, 3, EMO_TRAUMA), \
W("metatarsal",      0.55, 4, EMO_TRAUMA), \
W("periosteum",      0.55, 5, EMO_TRAUMA), \
W("duodenum",        0.50, 4, EMO_TRAUMA), \
W("thyroid",         0.55, 2, EMO_TRAUMA), \
W("ventricle",       0.60, 3, EMO_TRAUMA), \
W("membrane",        0.50, 2, EMO_TRAUMA), \
/* === ARCHITECTURE & EMPIRE === */ \
W("cathedral",       0.70, 3, EMO_VOID), \
W("colosseum",       0.65, 4, EMO_VOID), \
W("aqueduct",        0.60, 3, EMO_VOID), \
W("amphitheater",    0.65, 5, EMO_VOID), \
W("bureaucracy",     0.60, 4, EMO_VOID), \
W("chancellery",     0.55, 4, EMO_VOID), \
W("surveillance",    0.65, 3, EMO_TRAUMA), \
W("fortification",   0.60, 5, EMO_VOID), \
W("colonnade",       0.60, 3, EMO_VOID), \
W("parapet",         0.50, 3, EMO_VOID), \
W("granite",         0.55, 2, EMO_VOID), \
W("plaster",         0.40, 2, EMO_VOID), \
W("stucco",          0.40, 2, EMO_VOID), \
W("gutter",          0.45, 2, EMO_VOID), \
W("drainpipe",       0.40, 2, EMO_VOID), \
W("cupola",          0.55, 3, EMO_VOID), \
W("rotunda",         0.55, 3, EMO_VOID), \
W("obelisk",         0.55, 3, EMO_VOID), \
W("pediment",        0.50, 3, EMO_VOID), \
W("buttress",        0.55, 2, EMO_VOID), \
W("gargoyle",        0.55, 2, EMO_VOID), \
W("battlement",      0.55, 3, EMO_VOID), \
W("rampart",         0.55, 2, EMO_VOID), \
W("basilica",        0.60, 4, EMO_VOID), \
W("minaret",         0.50, 3, EMO_VOID), \
W("triumphal",       0.60, 3, EMO_VOID), \
W("cenotaph",        0.60, 3, EMO_VOID), \
W("mausoleum",       0.65, 4, EMO_VOID), \
/* === ABSTRACT HEAVY === */ \
W("predicament",     0.55, 4, EMO_JULIA), \
W("constellation",   0.65, 4, EMO_RESONANCE), \
W("thermodynamics",  0.60, 5, EMO_RESONANCE), \
W("hallucination",   0.60, 5, EMO_TRAUMA), \
W("hemorrhage",      0.70, 3, EMO_TRAUMA), \
W("bibliography",    0.45, 6, EMO_VOID), \
W("archaeology",     0.50, 5, EMO_VOID), \
W("inconsolable",    0.75, 5, EMO_JULIA), \
W("melancholy",      0.70, 4, EMO_JULIA), \
W("indifference",    0.60, 4, EMO_VOID), \
W("obsolescence",    0.55, 4, EMO_VOID), \
W("abandonment",     0.65, 4, EMO_JULIA), \
W("annihilation",    0.80, 5, EMO_TRAUMA), \
W("disintegration",  0.70, 5, EMO_TRAUMA), \
W("petrification",   0.65, 5, EMO_VOID), \
W("conflagration",   0.70, 4, EMO_TRAUMA), \
W("premonition",     0.60, 4, EMO_GRIEF), \
W("apprehension",    0.55, 4, EMO_GRIEF), \
W("lamentation",     0.65, 4, EMO_GRIEF), \
W("enumeration",     0.50, 5, EMO_VOID), \
W("perpetuation",    0.55, 5, EMO_RESONANCE), \
W("incarceration",   0.65, 5, EMO_TRAUMA), \
W("renunciation",    0.60, 5, EMO_VOID), \
W("desolation",      0.70, 4, EMO_GRIEF), \
W("transfiguration", 0.65, 5, EMO_RESONANCE), \
/* === NATURE — sparse, hard === */ \
W("tundra",          0.50, 2, EMO_VOID), \
W("fjord",           0.45, 1, EMO_VOID), \
W("glacier",         0.55, 2, EMO_VOID), \
W("basalt",          0.50, 2, EMO_VOID), \
W("obsidian",        0.55, 4, EMO_VOID), \
W("sediment",        0.45, 3, EMO_VOID), \
W("limestone",       0.45, 2, EMO_VOID), \
W("erosion",         0.50, 3, EMO_VOID), \
W("horizon",         0.55, 3, EMO_JULIA), \
W("equinox",         0.60, 3, EMO_RESONANCE), \
W("solstice",        0.60, 2, EMO_RESONANCE), \
W("stalactite",      0.50, 3, EMO_VOID), \
W("stalagmite",      0.50, 3, EMO_VOID), \
W("sandstone",       0.45, 2, EMO_VOID), \
W("pumice",          0.40, 2, EMO_VOID), \
W("lichen",          0.35, 2, EMO_VOID), \
W("estrangement",    0.55, 3, EMO_JULIA), \
/* === LIGHT WORDS — monosyllabic contrast === */ \
W("dust",            0.30, 1, EMO_VOID), \
W("ink",             0.35, 1, EMO_VOID), \
W("salt",            0.30, 1, EMO_VOID), \
W("bone",            0.50, 1, EMO_TRAUMA), \
W("tin",             0.25, 1, EMO_VOID), \
W("ash",             0.40, 1, EMO_VOID), \
W("cod",             0.20, 1, EMO_VOID), \
W("elm",             0.25, 1, EMO_VOID), \
W("fog",             0.30, 1, EMO_VOID), \
W("birch",           0.35, 1, EMO_JULIA), \
W("moss",            0.25, 1, EMO_VOID), \
W("rust",            0.40, 1, EMO_VOID), \
W("soot",            0.35, 1, EMO_VOID), \
W("wax",             0.25, 1, EMO_VOID), \
W("chalk",           0.30, 1, EMO_VOID), \
W("wool",            0.25, 1, EMO_TENDERNESS), \
W("slab",            0.35, 1, EMO_VOID), \
W("flint",           0.35, 1, EMO_VOID), \
W("peat",            0.30, 1, EMO_VOID), \
W("brine",           0.35, 1, EMO_VOID), \
W("grout",           0.30, 1, EMO_VOID), \
W("slag",            0.35, 1, EMO_VOID), \
W("thorn",           0.35, 1, EMO_TRAUMA), \
W("grime",           0.30, 1, EMO_VOID), \
W("filth",           0.40, 1, EMO_VOID), \
W("dross",           0.35, 1, EMO_VOID), \
W("bile",            0.40, 1, EMO_TRAUMA), \
W("kelp",            0.25, 1, EMO_VOID), \
W("shale",           0.30, 1, EMO_VOID), \
W("smelt",           0.35, 1, EMO_VOID), \
W("pith",            0.30, 1, EMO_VOID), \
W("dregs",           0.35, 1, EMO_VOID), \
/* === TIME & AGING === */ \
W("chronometer",     0.55, 4, EMO_VOID), \
W("hourglass",       0.55, 2, EMO_VOID), \
W("antiquity",       0.60, 4, EMO_VOID), \
W("obsolete",        0.50, 3, EMO_VOID), \
W("calendar",        0.45, 3, EMO_VOID), \
W("epoch",           0.55, 2, EMO_VOID), \
W("millennium",      0.60, 4, EMO_VOID), \
W("aftermath",       0.55, 3, EMO_TRAUMA), \
W("senescence",      0.55, 3, EMO_VOID), \
W("simultaneity",    0.60, 6, EMO_RESONANCE), \
W("anachronism",     0.55, 4, EMO_VOID), \
W("pendulum",        0.50, 3, EMO_VOID), \
W("sundial",         0.45, 2, EMO_VOID), \
W("posthumous",      0.60, 3, EMO_GRIEF), \
/* === WATER — Brodsky's Venice === */ \
W("lagoon",          0.50, 2, EMO_JULIA), \
W("canal",           0.45, 2, EMO_JULIA), \
W("gondola",         0.50, 3, EMO_JULIA), \
W("watermark",       0.55, 3, EMO_JULIA), \
W("acqua",           0.45, 2, EMO_JULIA), \
W("tide",            0.40, 1, EMO_RESONANCE), \
W("current",         0.40, 2, EMO_RESONANCE), \
W("undertow",        0.55, 3, EMO_TRAUMA), \
W("tributary",       0.50, 4, EMO_RESONANCE), \
W("inundation",      0.55, 4, EMO_TRAUMA), \
W("embankment",      0.50, 3, EMO_VOID), \
W("spillway",        0.45, 2, EMO_VOID), \
W("deluge",          0.55, 2, EMO_TRAUMA), \
W("cistern",         0.45, 2, EMO_VOID), \
W("bilge",           0.35, 1, EMO_VOID), \
W("brackish",        0.40, 2, EMO_VOID), \
W("adriatic",        0.55, 4, EMO_JULIA), \
/* === EXILE — central Brodsky theme === */ \
W("exile",           0.80, 2, EMO_JULIA), \
W("departure",       0.65, 3, EMO_JULIA), \
W("displacement",    0.60, 3, EMO_JULIA), \
W("immigration",     0.55, 4, EMO_JULIA), \
W("passport",        0.50, 2, EMO_JULIA), \
W("customs",         0.40, 2, EMO_JULIA), \
W("border",          0.55, 2, EMO_JULIA), \
W("checkpoint",      0.50, 2, EMO_TRAUMA), \
W("nowhere",         0.60, 2, EMO_VOID), \
W("elsewhere",       0.55, 2, EMO_JULIA), \
W("expatriate",      0.60, 4, EMO_JULIA), \
W("repatriation",    0.55, 5, EMO_JULIA), \
W("statelessness",   0.65, 3, EMO_VOID), \
W("motherland",      0.60, 3, EMO_JULIA), \
W("hinterland",      0.55, 3, EMO_VOID), \
W("banishment",      0.65, 3, EMO_JULIA), \
W("extradition",     0.60, 4, EMO_TRAUMA), \
/* === LANGUAGE & WRITING — Brodsky's poetics === */ \
W("consonant",       0.50, 3, EMO_RESONANCE), \
W("vowel",           0.45, 2, EMO_RESONANCE), \
W("syllable",        0.50, 3, EMO_RESONANCE), \
W("parenthesis",     0.50, 4, EMO_VOID), \
W("semicolon",       0.45, 4, EMO_VOID), \
W("apostrophe",      0.50, 4, EMO_VOID), \
W("manuscript",      0.55, 3, EMO_JULIA), \
W("typewriter",      0.55, 3, EMO_JULIA), \
W("postscript",      0.45, 2, EMO_VOID), \
W("translation",     0.55, 3, EMO_JULIA), \
W("nocturne",        0.55, 2, EMO_JULIA), \
W("lullaby",         0.50, 3, EMO_TENDERNESS), \
W("postcard",        0.45, 2, EMO_JULIA), \
W("elegy",           0.65, 3, EMO_GRIEF), \
W("stanza",          0.55, 2, EMO_RESONANCE), \
W("caesura",         0.60, 3, EMO_RESONANCE), \
W("enjambment",      0.55, 3, EMO_RESONANCE), \
W("prosody",         0.55, 3, EMO_RESONANCE), \
W("dactyl",          0.50, 2, EMO_RESONANCE), \
W("iamb",            0.50, 2, EMO_RESONANCE), \
W("trochee",         0.50, 2, EMO_RESONANCE), \
W("alexandrine",     0.55, 4, EMO_RESONANCE), \
W("rhetoric",        0.50, 3, EMO_VOID), \
W("epitaph",         0.60, 3, EMO_GRIEF), \
W("epigraph",        0.55, 3, EMO_VOID), \
W("palimpsest",      0.60, 3, EMO_RESONANCE), \
/* === DOMESTIC — Brodsky's rooms === */ \
W("ceiling",         0.40, 2, EMO_VOID), \
W("wallpaper",       0.35, 3, EMO_VOID), \
W("radiator",        0.40, 4, EMO_VOID), \
W("doorframe",       0.35, 2, EMO_VOID), \
W("windowsill",      0.40, 3, EMO_JULIA), \
W("floorboard",      0.35, 2, EMO_VOID), \
W("staircase",       0.45, 2, EMO_VOID), \
W("corridor",        0.45, 3, EMO_VOID), \
W("wardrobe",        0.35, 2, EMO_VOID), \
W("mattress",        0.30, 2, EMO_VOID), \
W("faucet",          0.35, 2, EMO_VOID), \
W("threshold",       0.50, 2, EMO_JULIA), \
W("linoleum",        0.40, 4, EMO_VOID), \
W("curtain",         0.35, 2, EMO_VOID), \
W("kettle",          0.35, 2, EMO_VOID), \
W("ashtray",         0.35, 2, EMO_VOID), \
W("bookshelf",       0.40, 2, EMO_JULIA), \
W("lightbulb",       0.35, 2, EMO_VOID), \
W("cupboard",        0.35, 2, EMO_VOID), \
W("bathtub",         0.30, 2, EMO_VOID), \
W("banister",        0.40, 3, EMO_VOID), \
W("clothesline",     0.35, 2, EMO_VOID), \
W("doorknob",        0.30, 2, EMO_VOID), \
W("lampshade",       0.35, 2, EMO_VOID), \
W("pillowcase",      0.30, 3, EMO_TENDERNESS), \
W("sideboard",       0.35, 2, EMO_VOID), \
W("tablecloth",      0.30, 2, EMO_VOID), \
/* === SCIENCE — Brodsky bridging physics and verse === */ \
W("government",      0.55, 3, EMO_VOID), \
W("population",      0.50, 4, EMO_VOID), \
W("photograph",      0.50, 3, EMO_JULIA), \
W("cigarette",       0.40, 3, EMO_VOID), \
W("telephone",       0.40, 3, EMO_JULIA), \
W("locomotive",      0.55, 4, EMO_VOID), \
W("mercury",         0.55, 4, EMO_RESONANCE), \
W("barometer",       0.50, 4, EMO_RESONANCE), \
W("oxygen",          0.45, 3, EMO_RESONANCE), \
W("hydrogen",        0.45, 3, EMO_RESONANCE), \
W("nitrogen",        0.40, 3, EMO_VOID), \
W("calcium",         0.40, 3, EMO_VOID), \
W("antimatter",      0.55, 4, EMO_RESONANCE), \
W("isotope",         0.50, 3, EMO_RESONANCE), \
W("centrifuge",      0.55, 3, EMO_RESONANCE), \
W("electron",        0.50, 3, EMO_RESONANCE), \
W("nucleus",         0.55, 3, EMO_RESONANCE), \
W("oscillation",     0.55, 4, EMO_RESONANCE), \
W("phosphorus",      0.50, 3, EMO_RESONANCE), \
W("formaldehyde",    0.50, 4, EMO_TRAUMA), \
W("stethoscope",     0.50, 3, EMO_TRAUMA), \
W("spectrometer",    0.55, 4, EMO_RESONANCE), \
/* === FUNCTION WORDS — minimal, for glue (mass >= 0.10) === */ \
W("that",            0.10, 1, EMO_VOID), \
W("which",           0.10, 1, EMO_VOID), \
W("where",           0.15, 1, EMO_VOID), \
W("when",            0.10, 1, EMO_VOID), \
W("not",             0.20, 1, EMO_VOID), \
W("nor",             0.25, 1, EMO_VOID), \
W("neither",         0.30, 2, EMO_VOID), \
W("without",         0.30, 2, EMO_VOID), \
W("beneath",         0.30, 2, EMO_VOID), \
W("against",         0.30, 2, EMO_VOID), \
W("beyond",          0.35, 2, EMO_JULIA), \
W("among",           0.25, 2, EMO_VOID), \
W("between",         0.30, 2, EMO_VOID), \
W("toward",          0.25, 2, EMO_JULIA), \
W("through",         0.25, 1, EMO_VOID), \
W("across",          0.30, 2, EMO_JULIA), \
W("above",           0.25, 2, EMO_VOID), \
W("below",           0.25, 2, EMO_VOID), \
W("nothing",         0.50, 2, EMO_VOID), \
W("nobody",          0.50, 3, EMO_VOID), \
W("everywhere",      0.40, 3, EMO_VOID), \
W("somewhere",       0.35, 2, EMO_JULIA), \
W("perhaps",         0.30, 2, EMO_VOID), \
W("always",          0.35, 2, EMO_VOID), \
W("never",           0.45, 2, EMO_VOID), \
W("once",            0.30, 1, EMO_JULIA), \
W("still",           0.35, 1, EMO_VOID), \
W("yet",             0.30, 1, EMO_VOID), \
W("already",         0.30, 3, EMO_VOID), \
W("henceforth",      0.35, 2, EMO_VOID), \
W("thereafter",      0.35, 3, EMO_VOID), \
W("nevertheless",    0.40, 4, EMO_VOID), \
W("notwithstanding", 0.40, 4, EMO_VOID), \
/* === VERBS — heavy, mechanical, domain-bridging === */ \
W("calcify",         0.55, 3, EMO_VOID), \
W("deteriorate",     0.60, 4, EMO_TRAUMA), \
W("disintegrate",    0.65, 4, EMO_TRAUMA), \
W("petrify",         0.60, 3, EMO_VOID), \
W("corrode",         0.55, 2, EMO_TRAUMA), \
W("erode",           0.50, 2, EMO_VOID), \
W("ossify",          0.55, 3, EMO_VOID), \
W("congeal",         0.50, 2, EMO_VOID), \
W("crystallize",     0.55, 3, EMO_RESONANCE), \
W("evaporate",       0.50, 4, EMO_VOID), \
W("accumulate",      0.50, 4, EMO_VOID), \
W("accelerate",      0.50, 4, EMO_RESONANCE), \
W("reverberate",     0.55, 4, EMO_RESONANCE), \
W("disembark",       0.50, 3, EMO_JULIA), \
W("navigate",        0.45, 3, EMO_RESONANCE), \
W("approximate",     0.45, 4, EMO_RESONANCE), \
W("remember",        0.50, 3, EMO_JULIA), \
W("forget",          0.50, 2, EMO_VOID), \
W("abandon",         0.60, 3, EMO_JULIA), \
W("surrender",       0.55, 3, EMO_VOID), \
W("resemble",        0.40, 3, EMO_RESONANCE), \
W("diminish",        0.50, 3, EMO_VOID), \
W("extinguish",      0.55, 3, EMO_VOID), \
W("inhabit",         0.45, 3, EMO_JULIA), \
W("penetrate",       0.50, 3, EMO_TRAUMA), \
W("illuminate",      0.50, 4, EMO_RESONANCE), \
W("obliterate",      0.65, 4, EMO_TRAUMA), \
W("decompose",       0.55, 3, EMO_TRAUMA), \
W("fossilize",       0.50, 3, EMO_VOID), \
W("oxidize",         0.50, 3, EMO_VOID), \
W("coagulate",       0.50, 4, EMO_TRAUMA), \
W("metastasize",     0.60, 4, EMO_TRAUMA), \
W("proliferate",     0.55, 4, EMO_RESONANCE), \
W("amalgamate",      0.50, 4, EMO_RESONANCE), \
W("circumnavigate",  0.55, 5, EMO_RESONANCE), \
W("interrogate",     0.55, 4, EMO_TRAUMA), \
W("confiscate",      0.55, 3, EMO_TRAUMA), \
W("domesticate",     0.50, 4, EMO_VOID), \
W("procrastinate",   0.45, 4, EMO_VOID), \
W("contaminate",     0.55, 4, EMO_TRAUMA), \
W("perpetuate",      0.55, 4, EMO_RESONANCE), \
W("repatriate",      0.55, 4, EMO_JULIA), \
W("asphyxiate",      0.65, 4, EMO_TRAUMA), \
W("disseminate",     0.50, 4, EMO_VOID), \
W("exacerbate",      0.55, 4, EMO_TRAUMA), \
W("capitulate",      0.55, 4, EMO_VOID), \
W("dislocate",       0.55, 3, EMO_TRAUMA), \
W("submerge",        0.50, 2, EMO_VOID), \
W("transfix",        0.55, 2, EMO_RESONANCE), \
W("envelop",         0.45, 3, EMO_VOID), \
W("supplant",        0.50, 2, EMO_VOID), \
W("transmute",       0.55, 2, EMO_RESONANCE), \
W("subjugate",       0.60, 3, EMO_TRAUMA), \
W("desiccate",       0.50, 3, EMO_VOID), \
W("bifurcate",       0.50, 3, EMO_RESONANCE), \
W("attenuate",       0.50, 4, EMO_VOID), \
W("reconstitute",    0.50, 4, EMO_RESONANCE), \
W("transubstantiate",0.60, 5, EMO_RESONANCE), \
/* === GEOGRAPHY — Brodsky's compass === */ \
W("promontory",      0.55, 4, EMO_VOID), \
W("isthmus",         0.50, 2, EMO_VOID), \
W("continental",     0.55, 4, EMO_VOID), \
W("topography",      0.55, 4, EMO_RESONANCE), \
W("Mediterranean",   0.60, 6, EMO_JULIA), \
W("Scandinavian",    0.55, 5, EMO_VOID), \
W("steppe",          0.50, 1, EMO_VOID), \
W("taiga",           0.45, 2, EMO_VOID), \
W("plateau",         0.45, 2, EMO_VOID), \
W("ravine",          0.45, 2, EMO_VOID), \
W("watershed",       0.50, 3, EMO_VOID), \
W("sargasso",        0.45, 3, EMO_VOID), \
/* === EMPIRE CONCEPTS === */ \
W("imperium",        0.70, 4, EMO_VOID), \
W("hegemony",        0.65, 4, EMO_VOID), \
W("absolutism",      0.60, 4, EMO_VOID), \
W("totalitarian",    0.65, 6, EMO_TRAUMA), \
W("propaganda",      0.55, 4, EMO_VOID), \
W("jurisdiction",    0.55, 4, EMO_VOID), \
W("conscription",    0.60, 3, EMO_TRAUMA), \
W("insurrection",    0.60, 4, EMO_RAGE), \
W("subjugation",     0.65, 4, EMO_TRAUMA), \
W("emancipation",    0.55, 5, EMO_DESIRE), \
/* === EMOTIONS — Brodsky's range === */ \
W("nostalgia",       0.65, 4, EMO_JULIA), \
W("ennui",           0.55, 2, EMO_VOID), \
W("vertigo",         0.55, 3, EMO_TRAUMA), \
W("claustrophobia",  0.60, 5, EMO_TRAUMA), \
W("agoraphobia",     0.55, 5, EMO_TRAUMA), \
W("euphoria",        0.55, 4, EMO_JOY), \
W("torpor",          0.50, 2, EMO_VOID), \
W("stupefaction",    0.55, 4, EMO_VOID), \
W("exhilaration",    0.50, 5, EMO_JOY), \
W("repugnance",      0.60, 3, EMO_RAGE), \
W("remorse",         0.60, 2, EMO_GRIEF), \
W("bereavement",     0.65, 3, EMO_GRIEF), \
/* === OBJECTS — particular, not generic === */ \
W("samovar",         0.50, 3, EMO_JULIA), \
W("chandelier",      0.50, 3, EMO_VOID), \
W("metronome",       0.50, 3, EMO_RESONANCE), \
W("gramophone",      0.50, 3, EMO_JULIA), \
W("telescope",       0.50, 3, EMO_RESONANCE), \
W("microscope",      0.50, 3, EMO_RESONANCE), \
W("thermometer",     0.50, 4, EMO_VOID), \
W("perambulator",    0.45, 5, EMO_VOID), \
W("sarcophagus",     0.65, 4, EMO_VOID), \
W("reliquary",       0.55, 4, EMO_VOID), \
/* === FABRIC & MATERIAL === */ \
W("porcelain",       0.45, 3, EMO_VOID), \
W("terracotta",      0.45, 4, EMO_VOID), \
W("mahogany",        0.45, 4, EMO_VOID), \
W("parchment",       0.50, 2, EMO_JULIA), \
W("burlap",          0.35, 2, EMO_VOID), \
W("asbestos",        0.45, 3, EMO_TRAUMA), \
W("quicksilver",     0.55, 3, EMO_RESONANCE), \
W("tungsten",        0.50, 2, EMO_VOID), \
/* === BRODSKY POEM WORDS — specific to his English verse === */ \
W("lozenge",         0.40, 2, EMO_VOID), \
W("chrysanthemum",   0.45, 4, EMO_JULIA), \
W("sextant",         0.50, 2, EMO_RESONANCE), \
W("declension",      0.50, 3, EMO_RESONANCE), \
W("genitive",        0.45, 3, EMO_RESONANCE), \
W("ablative",        0.50, 3, EMO_VOID), \
W("accusative",      0.50, 4, EMO_VOID), \
W("nominative",      0.50, 4, EMO_VOID), \
W("taxonomy",        0.50, 4, EMO_VOID), \
W("cartesian",       0.50, 3, EMO_RESONANCE), \
W("euclidean",       0.55, 4, EMO_RESONANCE), \
W("copernican",      0.55, 4, EMO_RESONANCE), \
W("ptolemaic",       0.55, 4, EMO_VOID), \
W("newtonian",       0.50, 4, EMO_RESONANCE), \
/* === ADDITIONAL — reaching 500 === */ \
W("insufferable",    0.55, 4, EMO_RAGE), \
W("irrevocable",     0.65, 4, EMO_GRIEF), \
W("irreversible",    0.65, 5, EMO_GRIEF), \
W("imperceptible",   0.50, 5, EMO_VOID), \
W("uninhabitable",   0.55, 5, EMO_VOID), \
W("impenetrable",    0.60, 5, EMO_VOID), \
W("interminable",    0.55, 5, EMO_VOID), \
W("immovable",       0.55, 4, EMO_VOID), \
W("unforgivable",    0.65, 5, EMO_RAGE), \
W("inconceivable",   0.55, 5, EMO_VOID), \
W("carbuncle",       0.50, 3, EMO_TRAUMA), \
W("gangrene",        0.60, 2, EMO_TRAUMA), \
W("tourniquet",      0.55, 3, EMO_TRAUMA), \
W("cauterize",       0.55, 3, EMO_TRAUMA), \
W("suture",          0.50, 2, EMO_TRAUMA), \
W("amputation",      0.65, 4, EMO_TRAUMA), \
W("anesthesia",      0.50, 4, EMO_VOID), \
W("metabolism",      0.50, 4, EMO_RESONANCE), \
W("penmanship",      0.50, 3, EMO_JULIA), \
W("typeface",        0.45, 2, EMO_VOID), \
W("colophon",        0.50, 3, EMO_VOID), \
W("frontispiece",    0.50, 3, EMO_VOID), \
W("footnote",        0.40, 2, EMO_VOID), \
W("marginalia",      0.50, 5, EMO_JULIA), \
W("interlocutor",    0.50, 5, EMO_VOID), \
W("soliloquy",       0.55, 4, EMO_JULIA), \
W("monologue",       0.50, 3, EMO_VOID), \
W("apostasy",        0.55, 4, EMO_VOID), \
W("catechism",       0.50, 3, EMO_VOID), \
W("genuflection",    0.50, 4, EMO_VOID), \
W("requiem",         0.65, 3, EMO_GRIEF), \
W("liturgy",         0.55, 3, EMO_VOID), \
W("sepulcher",       0.60, 3, EMO_GRIEF), \
W("ossuary",         0.55, 4, EMO_GRIEF), \
W("excommunication", 0.60, 6, EMO_TRAUMA), \
W("tabernacle",      0.55, 4, EMO_VOID), \
/* === MODERN/URBAN — the century Brodsky inhabited === */ \
W("subway",          0.45, 2, EMO_VOID), \
W("asphalt",         0.50, 2, EMO_VOID), \
W("neon",            0.40, 2, EMO_VOID), \
W("billboard",       0.45, 2, EMO_VOID), \
W("antenna",         0.45, 3, EMO_VOID), \
W("satellite",       0.50, 3, EMO_RESONANCE), \
W("escalator",       0.45, 4, EMO_VOID), \
W("concrete",        0.50, 2, EMO_VOID), \
W("diesel",          0.40, 2, EMO_VOID), \
W("plastic",         0.35, 2, EMO_VOID), \
W("aluminum",        0.40, 4, EMO_VOID), \
W("fiberglass",      0.40, 3, EMO_VOID), \
W("silicon",         0.45, 3, EMO_RESONANCE), \
W("fluorescent",     0.45, 3, EMO_VOID), \
W("transistor",      0.50, 3, EMO_RESONANCE), \
W("turbine",         0.50, 2, EMO_VOID), \
W("generator",       0.45, 4, EMO_VOID), \
W("transformer",     0.50, 3, EMO_RESONANCE), \
W("overpass",        0.45, 3, EMO_VOID), \
W("underpass",       0.40, 3, EMO_VOID), \
W("crosswalk",       0.40, 2, EMO_VOID), \
W("boulevard",       0.50, 3, EMO_JULIA), \
W("tenement",        0.50, 3, EMO_VOID), \
W("smokestacks",     0.50, 2, EMO_VOID), \
/* === VERBS OF PERCEPTION — what Brodsky's eye does === */ \
W("perceive",        0.50, 2, EMO_RESONANCE), \
W("overhear",        0.45, 3, EMO_RESONANCE), \
W("glimpse",         0.45, 1, EMO_JULIA), \
W("squint",          0.40, 1, EMO_VOID), \
W("grope",           0.40, 1, EMO_TRAUMA), \
W("stumble",         0.40, 2, EMO_TRAUMA), \
W("fumble",          0.35, 2, EMO_VOID), \
W("stammer",         0.45, 2, EMO_TRAUMA), \
W("mutter",          0.40, 2, EMO_VOID), \
W("shudder",         0.50, 2, EMO_TRAUMA), \
W("flinch",          0.45, 1, EMO_TRAUMA), \
W("wince",           0.40, 1, EMO_TRAUMA), \
W("gaze",            0.35, 1, EMO_JULIA), \
W("scrutinize",      0.50, 3, EMO_VOID), \
W("discern",         0.50, 2, EMO_RESONANCE), \
W("recollect",       0.50, 3, EMO_JULIA), \
/* === CONNECTIVE TISSUE — bureaucratic syntax === */ \
W("therefore",       0.35, 2, EMO_VOID), \
W("moreover",        0.35, 3, EMO_VOID), \
W("whereas",         0.30, 2, EMO_VOID), \
W("inasmuch",        0.35, 3, EMO_VOID), \
W("accordingly",     0.35, 4, EMO_VOID), \
W("furthermore",     0.35, 3, EMO_VOID), \
W("insofar",         0.30, 3, EMO_VOID), \
W("heretofore",      0.35, 3, EMO_VOID), \
W("whereby",         0.30, 2, EMO_VOID), \
W("albeit",          0.35, 3, EMO_VOID), \
W("namely",          0.30, 2, EMO_VOID), \
W("hitherto",        0.35, 3, EMO_VOID), \
/* === FOOD & DRINK — Brodsky's ordinary life === */ \
W("coffee",          0.35, 2, EMO_JULIA), \
W("vodka",           0.40, 2, EMO_JULIA), \
W("herring",         0.35, 2, EMO_VOID), \
W("bread",           0.30, 1, EMO_TENDERNESS), \
W("vinegar",         0.35, 3, EMO_VOID), \
W("mustard",         0.30, 2, EMO_VOID), \
W("pepper",          0.30, 2, EMO_VOID), \
W("porridge",        0.30, 2, EMO_VOID), \
W("cabbage",         0.30, 2, EMO_VOID), \
W("marmalade",       0.35, 3, EMO_VOID), \
W("rye",             0.30, 1, EMO_VOID), \
W("kvass",           0.30, 1, EMO_JULIA), \
W("broth",           0.30, 1, EMO_TENDERNESS), \
W("crust",           0.30, 1, EMO_VOID), \
/* === CLOTHING — what the exile wears === */ \
W("overcoat",        0.50, 3, EMO_JULIA), \
W("galosh",          0.35, 2, EMO_VOID), \
W("lapel",           0.40, 2, EMO_VOID), \
W("cufflink",        0.35, 2, EMO_VOID), \
W("suspender",       0.40, 3, EMO_VOID), \
W("collar",          0.35, 2, EMO_VOID), \
W("buttonhole",      0.35, 3, EMO_VOID), \
W("epaulette",       0.45, 3, EMO_VOID), \
W("gabardine",       0.40, 3, EMO_VOID), \
W("trouser",         0.35, 2, EMO_VOID), \
W("mackintosh",      0.45, 3, EMO_JULIA), \
W("waistcoat",       0.40, 2, EMO_VOID), \
/* === MEDICAL VERBS — the body as administered === */ \
W("diagnose",        0.55, 3, EMO_TRAUMA), \
W("amputate",        0.60, 3, EMO_TRAUMA), \
W("anesthetize",     0.55, 4, EMO_VOID), \
W("resuscitate",     0.55, 4, EMO_RESONANCE), \
W("hemorrhaging",    0.65, 4, EMO_TRAUMA), \
W("inoculate",       0.50, 4, EMO_VOID), \
W("administer",      0.50, 4, EMO_VOID), \
W("prescribe",       0.45, 2, EMO_VOID), \
W("palpitate",       0.55, 3, EMO_TRAUMA), \
W("atrophy",         0.55, 3, EMO_TRAUMA), \
/* === MONOSYLLABLES FOR CONTRAST — grit in the gears === */ \
W("grit",            0.35, 1, EMO_VOID), \
W("swill",           0.30, 1, EMO_VOID), \
W("blight",          0.45, 1, EMO_TRAUMA), \
W("smog",            0.35, 1, EMO_VOID), \
W("scab",            0.40, 1, EMO_TRAUMA), \
W("clot",            0.40, 1, EMO_TRAUMA), \
W("rag",             0.25, 1, EMO_VOID), \
W("rut",             0.30, 1, EMO_VOID), \
W("mire",            0.35, 1, EMO_VOID), \
W("silt",            0.30, 1, EMO_VOID), \
W("scum",            0.35, 1, EMO_VOID), \
W("gall",            0.40, 1, EMO_TRAUMA), \
W("dint",            0.25, 1, EMO_VOID), \
W("burr",            0.25, 1, EMO_VOID), \
W("caulk",           0.30, 1, EMO_VOID), \
W("chaff",           0.25, 1, EMO_VOID), \
W("spore",           0.30, 1, EMO_VOID), \
W("suet",            0.25, 1, EMO_VOID), \
W("tripe",           0.30, 1, EMO_VOID), \
W("tallow",          0.30, 2, EMO_VOID), \
/* === BUREAUCRATIC/LEGAL — the empire's paperwork === */ \
W("memorandum",      0.50, 4, EMO_VOID), \
W("affidavit",       0.50, 4, EMO_VOID), \
W("requisition",     0.50, 4, EMO_VOID), \
W("subcommittee",    0.50, 4, EMO_VOID), \
W("adjudicate",      0.50, 4, EMO_VOID), \
W("promulgate",      0.50, 3, EMO_VOID), \
W("plenipotentiary", 0.55, 6, EMO_VOID), \
W("ratification",    0.50, 5, EMO_VOID), \
W("tribunal",        0.55, 3, EMO_TRAUMA), \
W("deposition",      0.50, 4, EMO_VOID), \
W("notarize",        0.40, 3, EMO_VOID), \
W("protocol",        0.50, 3, EMO_VOID), \
W("ordinance",       0.50, 3, EMO_VOID), \
W("statute",         0.45, 2, EMO_VOID), \
W("amendment",       0.45, 3, EMO_VOID), \
W("quorum",          0.45, 2, EMO_VOID), \
W("convene",         0.45, 2, EMO_VOID), \
W("stipulate",       0.45, 3, EMO_VOID), \
W("ratify",          0.45, 3, EMO_VOID), \
/* === ADDITIONAL BRODSKY — reaching 650 === */ \
W("acquittal",       0.55, 3, EMO_VOID), \
W("inventory",       0.45, 4, EMO_VOID), \
W("communique",      0.50, 3, EMO_VOID), \
W("commissariat",    0.55, 4, EMO_VOID), \
W("apparatus",       0.55, 4, EMO_VOID), \
W("municipality",    0.50, 6, EMO_VOID), \
W("cadastral",       0.45, 3, EMO_VOID), \
W("cartouche",       0.50, 2, EMO_VOID), \
W("vestibule",       0.45, 3, EMO_VOID), \
W("administrate",    0.50, 4, EMO_VOID), \
W("dossier",         0.45, 2, EMO_VOID), \
W("gazette",         0.40, 2, EMO_VOID), \
W("provenance",      0.50, 3, EMO_VOID), \
W("sinew",           0.40, 2, EMO_TRAUMA), \
W("marrow",          0.45, 2, EMO_TRAUMA), \
W("pylorus",         0.50, 3, EMO_TRAUMA), \
W("precipice",       0.55, 3, EMO_TRAUMA), \
W("cadastre",        0.45, 2, EMO_VOID), \
W("declassify",      0.50, 4, EMO_VOID), \
W("adjournment",     0.50, 3, EMO_VOID), \
W("moratorium",      0.50, 5, EMO_VOID), \
W("recidivism",      0.50, 4, EMO_VOID), \
W("armistice",       0.55, 3, EMO_VOID), \
/* === PLATH — DOMESTIC HORROR === */ \
W("oven",            0.60, 2, EMO_TRAUMA), \
W("nursery",         0.50, 3, EMO_TRAUMA), \
W("mirror",          0.45, 2, EMO_TRAUMA), \
W("razor",           0.55, 2, EMO_TRAUMA), \
W("jar",             0.35, 1, EMO_TRAUMA), \
W("specimen",        0.55, 3, EMO_TRAUMA), \
W("electrode",       0.55, 3, EMO_TRAUMA), \
W("incubator",       0.50, 4, EMO_TRAUMA), \
W("autopsy",         0.65, 3, EMO_TRAUMA), \
W("bell",            0.35, 1, EMO_TRAUMA), \
W("gauze",           0.35, 1, EMO_TRAUMA), \
W("scalpel",         0.55, 2, EMO_TRAUMA), \
W("forceps",         0.50, 2, EMO_TRAUMA), \
W("catheter",        0.50, 3, EMO_TRAUMA), \
W("gurney",          0.45, 2, EMO_TRAUMA), \
W("stirrup",         0.45, 2, EMO_TRAUMA), \
W("speculum",        0.55, 3, EMO_TRAUMA), \
W("swab",            0.30, 1, EMO_TRAUMA), \
W("syringe",         0.50, 2, EMO_TRAUMA), \
/* === PLATH — BODY (FEMALE, VISCERAL) === */ \
W("placenta",        0.65, 3, EMO_TRAUMA), \
W("uterus",          0.60, 3, EMO_TRAUMA), \
W("ovary",           0.55, 3, EMO_TRAUMA), \
W("cervix",          0.55, 2, EMO_TRAUMA), \
W("nipple",          0.40, 2, EMO_TRAUMA), \
W("lactate",         0.45, 2, EMO_TRAUMA), \
W("umbilical",       0.55, 4, EMO_TRAUMA), \
W("menstrual",       0.55, 3, EMO_TRAUMA), \
W("amniotic",        0.55, 4, EMO_TRAUMA), \
W("fallopian",       0.55, 4, EMO_TRAUMA), \
W("vulva",           0.50, 2, EMO_TRAUMA), \
W("episiotomy",      0.60, 6, EMO_TRAUMA), \
W("colostrum",       0.50, 3, EMO_TRAUMA), \
/* === CELAN — BROKEN LANGUAGE === */ \
W("morpheme",        0.50, 2, EMO_RESONANCE), \
W("phoneme",         0.50, 2, EMO_RESONANCE), \
W("grapheme",        0.50, 2, EMO_RESONANCE), \
W("erasure",         0.55, 3, EMO_GRIEF), \
W("lacuna",          0.55, 3, EMO_GRIEF), \
W("redaction",       0.55, 3, EMO_TRAUMA), \
W("elision",         0.50, 3, EMO_GRIEF), \
W("aphasic",         0.55, 3, EMO_TRAUMA), \
W("glottal",         0.45, 2, EMO_RESONANCE), \
W("fricative",       0.50, 3, EMO_RESONANCE), \
W("plosive",         0.45, 2, EMO_RESONANCE), \
W("diphthong",       0.50, 2, EMO_RESONANCE), \
W("ligature",        0.50, 3, EMO_RESONANCE), \
/* === CELAN — ABSENCE === */ \
W("neve",            0.40, 2, EMO_GRIEF), \
W("cinder",          0.45, 2, EMO_GRIEF), \
W("char",            0.40, 1, EMO_GRIEF), \
W("residue",         0.45, 3, EMO_VOID), \
W("trace",           0.40, 1, EMO_GRIEF), \
W("remnant",         0.50, 2, EMO_GRIEF), \
W("vestige",         0.50, 2, EMO_GRIEF), \
W("afterimage",      0.45, 3, EMO_GRIEF), \
W("hollow",          0.40, 2, EMO_VOID), \
W("void",            0.55, 1, EMO_VOID), \
W("absence",         0.55, 2, EMO_GRIEF), \
W("nullity",         0.50, 3, EMO_VOID), \
/* === WEATHER / ATMOSPHERE === */ \
W("drizzle",         0.30, 2, EMO_VOID), \
W("sleet",           0.35, 1, EMO_VOID), \
W("haze",            0.30, 1, EMO_VOID), \
W("overcast",        0.35, 3, EMO_VOID), \
W("muggy",           0.25, 2, EMO_VOID), \
W("swelter",         0.40, 2, EMO_VOID), \
W("gust",            0.35, 1, EMO_VOID), \
W("squall",          0.45, 1, EMO_TRAUMA), \
W("tempest",         0.55, 2, EMO_TRAUMA), \
W("drought",         0.50, 1, EMO_VOID), \
W("hoarfrost",       0.45, 2, EMO_VOID), \
W("downpour",        0.40, 2, EMO_VOID), \
/* === TEXTURE / SENSATION === */ \
W("gritty",          0.35, 2, EMO_VOID), \
W("viscous",         0.45, 2, EMO_VOID), \
W("abrasive",        0.45, 3, EMO_TRAUMA), \
W("coarse",          0.35, 1, EMO_VOID), \
W("granular",        0.40, 3, EMO_VOID), \
W("porous",          0.40, 2, EMO_VOID), \
W("brittle",         0.45, 2, EMO_TRAUMA), \
W("supple",          0.35, 2, EMO_TENDERNESS), \
W("taut",            0.40, 1, EMO_VOID), \
W("slack",           0.30, 1, EMO_VOID), \
W("limp",            0.30, 1, EMO_VOID), \
W("clammy",          0.35, 2, EMO_TRAUMA), \
/* === SOUND === */ \
W("clatter",         0.40, 2, EMO_VOID), \
W("creak",           0.35, 1, EMO_VOID), \
W("rasp",            0.40, 1, EMO_TRAUMA), \
W("gurgle",          0.35, 2, EMO_VOID), \
W("wheeze",          0.45, 1, EMO_TRAUMA), \
W("rattle",          0.40, 2, EMO_TRAUMA), \
W("hiss",            0.35, 1, EMO_VOID), \
W("drone",           0.35, 1, EMO_VOID), \
W("throb",           0.45, 1, EMO_TRAUMA), \
W("thud",            0.40, 1, EMO_VOID), \
W("clang",           0.40, 1, EMO_VOID), \
W("screech",         0.45, 1, EMO_TRAUMA), \
W("groan",           0.40, 1, EMO_GRIEF), \
/* === INSECTS / SMALL LIFE === */ \
W("moth",            0.35, 1, EMO_VOID), \
W("cockroach",       0.40, 2, EMO_VOID), \
W("centipede",       0.40, 3, EMO_VOID), \
W("maggot",          0.45, 2, EMO_TRAUMA), \
W("larva",           0.40, 2, EMO_VOID), \
W("chrysalis",       0.45, 3, EMO_RESONANCE), \
W("pupa",            0.35, 2, EMO_VOID), \
W("termite",         0.40, 2, EMO_VOID), \
W("mite",            0.25, 1, EMO_VOID), \
W("louse",           0.30, 1, EMO_VOID), \
W("weevil",          0.35, 2, EMO_VOID), \
W("cicada",          0.40, 3, EMO_VOID), \
/* === TOOLS === */ \
W("wrench",          0.40, 1, EMO_VOID), \
W("pliers",          0.40, 2, EMO_VOID), \
W("awl",             0.35, 1, EMO_VOID), \
W("chisel",          0.40, 2, EMO_VOID), \
W("vise",            0.40, 1, EMO_VOID), \
W("clamp",           0.35, 1, EMO_VOID), \
W("lathe",           0.40, 1, EMO_VOID), \
W("rivet",           0.35, 2, EMO_VOID), \
W("solder",          0.40, 2, EMO_VOID), \
W("gimlet",          0.35, 2, EMO_VOID), \
W("anvil",           0.45, 2, EMO_VOID), \
W("trowel",          0.35, 1, EMO_VOID), \
/* === PLATH — ADDITIONAL DOMESTIC === */ \
W("liniment",        0.40, 3, EMO_TRAUMA), \
W("iodine",          0.45, 3, EMO_TRAUMA), \
W("bandage",         0.35, 2, EMO_TRAUMA), \
W("splint",          0.40, 1, EMO_TRAUMA), \
W("crib",            0.35, 1, EMO_TRAUMA), \
W("bassinet",        0.40, 3, EMO_TRAUMA), \
W("cradle",          0.40, 2, EMO_TRAUMA), \
W("diaper",          0.30, 3, EMO_TRAUMA), \
W("formula",         0.35, 3, EMO_VOID), \
W("stroller",        0.35, 2, EMO_VOID), \
W("cisternae",       0.50, 3, EMO_TRAUMA), \
W("curettage",       0.55, 3, EMO_TRAUMA), \
W("retractor",       0.50, 3, EMO_TRAUMA), \
/* === CELAN — ADDITIONAL ABSENCE === */ \
W("rubble",          0.40, 2, EMO_GRIEF), \
W("debris",          0.45, 2, EMO_GRIEF), \
W("detritus",        0.50, 3, EMO_VOID), \
W("efface",          0.45, 2, EMO_GRIEF), \
W("occlude",         0.45, 2, EMO_VOID), \
W("oblique",         0.45, 2, EMO_VOID), \
W("opacity",         0.45, 4, EMO_VOID), \
W("penumbra",        0.50, 3, EMO_GRIEF), \
W("umbra",           0.45, 2, EMO_GRIEF), \
W("silhouette",      0.45, 3, EMO_GRIEF), \
W("specter",         0.50, 2, EMO_GRIEF), \
/* === CELAN — ADDITIONAL LANGUAGE === */ \
W("bilabial",        0.45, 4, EMO_RESONANCE), \
W("alveolar",        0.45, 4, EMO_RESONANCE), \
W("sibilant",        0.45, 3, EMO_RESONANCE), \
W("guttural",        0.50, 3, EMO_RESONANCE), \
W("uvular",          0.45, 3, EMO_RESONANCE), \
W("aspirate",        0.45, 3, EMO_RESONANCE), \
/* === ADDITIONAL WEATHER === */ \
W("nimbus",          0.40, 2, EMO_VOID), \
W("cumulus",         0.40, 3, EMO_VOID), \
W("cirrus",          0.35, 2, EMO_VOID), \
W("stratus",         0.35, 2, EMO_VOID), \
W("monsoon",         0.45, 2, EMO_VOID), \
W("sirocco",         0.45, 3, EMO_VOID), \
W("mistral",         0.45, 2, EMO_VOID), \
/* === ADDITIONAL TEXTURE === */ \
W("callous",         0.45, 2, EMO_VOID), \
W("fibrous",         0.40, 2, EMO_VOID), \
W("calcified",       0.45, 3, EMO_VOID), \
W("serrated",        0.45, 3, EMO_VOID), \
W("corrugated",      0.45, 4, EMO_VOID), \
/* END */
