/* inhale/en.h — English heavy vocabulary for brodsky.c
 * ~300 words. Latinisms, polysyllables, Brodsky's actual lexicon.
 * Each word: text, mass, syllables, emotion, consonant_density (precomputed)
 */

/* W(word, mass, syllables, emotion) */
#define INHALE_EN \
/* === HEAVY ETERNALS === */ \
W("death",           0.95, 1, EMO_TRAUMA), \
W("empire",          0.85, 2, EMO_VOID), \
W("infinity",        0.80, 5, EMO_RESONANCE), \
W("sovereignty",     0.75, 4, EMO_VOID), \
W("eternity",        0.80, 4, EMO_RESONANCE), \
W("consciousness",   0.70, 3, EMO_RESONANCE), \
W("civilization",    0.65, 5, EMO_VOID), \
W("architecture",    0.70, 4, EMO_RESONANCE), \
W("metamorphosis",   0.75, 5, EMO_RESONANCE), \
W("deterioration",   0.70, 6, EMO_TRAUMA), \
/* === BRODSKY LEXICON — from actual poems === */ \
W("province",        0.60, 2, EMO_JULIA), \
W("column",          0.55, 2, EMO_VOID), \
W("portico",         0.60, 3, EMO_VOID), \
W("facade",          0.55, 2, EMO_VOID), \
W("cornice",         0.50, 2, EMO_VOID), \
W("balustrade",      0.60, 3, EMO_VOID), \
W("marble",          0.65, 2, EMO_VOID), \
W("gravel",          0.40, 2, EMO_VOID), \
W("cobblestone",     0.50, 3, EMO_VOID), \
W("estuary",         0.55, 4, EMO_RESONANCE), \
W("quay",            0.45, 1, EMO_JULIA), \
W("pier",            0.40, 1, EMO_JULIA), \
W("longitude",       0.55, 3, EMO_RESONANCE), \
W("latitude",        0.55, 3, EMO_RESONANCE), \
W("meridian",        0.60, 4, EMO_RESONANCE), \
W("hemisphere",      0.60, 3, EMO_VOID), \
W("peninsula",       0.55, 4, EMO_JULIA), \
W("cartography",     0.60, 4, EMO_RESONANCE), \
W("permafrost",      0.65, 3, EMO_VOID), \
W("archipelago",     0.55, 5, EMO_RESONANCE), \
/* === GEOMETRY — Brodsky loved geometry === */ \
W("perpendicular",   0.65, 5, EMO_RESONANCE), \
W("tangent",         0.50, 2, EMO_RESONANCE), \
W("parabola",        0.60, 4, EMO_RESONANCE), \
W("hyperbola",       0.55, 4, EMO_RESONANCE), \
W("asymptote",       0.60, 3, EMO_JULIA), \
W("intersection",    0.55, 4, EMO_RESONANCE), \
W("circumference",   0.60, 4, EMO_RESONANCE), \
W("diagonal",        0.50, 4, EMO_RESONANCE), \
W("parallel",        0.55, 3, EMO_RESONANCE), \
W("trapezoid",       0.50, 3, EMO_RESONANCE), \
W("vector",          0.55, 2, EMO_RESONANCE), \
W("rectangle",       0.45, 3, EMO_RESONANCE), \
/* === BODY — grotesque, not tender === */ \
W("vertebra",        0.70, 3, EMO_TRAUMA), \
W("cartilage",       0.60, 3, EMO_TRAUMA), \
W("ligament",        0.55, 3, EMO_TRAUMA), \
W("tendon",          0.55, 2, EMO_TRAUMA), \
W("sternum",         0.65, 2, EMO_TRAUMA), \
W("larynx",          0.60, 2, EMO_TRAUMA), \
W("pharynx",         0.55, 2, EMO_TRAUMA), \
W("esophagus",       0.55, 4, EMO_TRAUMA), \
W("abdomen",         0.50, 3, EMO_TRAUMA), \
W("diaphragm",       0.60, 3, EMO_TRAUMA), \
W("collarbone",      0.55, 3, EMO_TRAUMA), \
W("ribcage",         0.60, 2, EMO_TRAUMA), \
W("skull",           0.70, 1, EMO_TRAUMA), \
W("spine",           0.65, 1, EMO_TRAUMA), \
/* === ARCHITECTURE & EMPIRE === */ \
W("cathedral",       0.70, 3, EMO_VOID), \
W("colosseum",       0.65, 4, EMO_VOID), \
W("aqueduct",        0.60, 3, EMO_VOID), \
W("amphitheater",    0.65, 5, EMO_VOID), \
W("bureaucracy",     0.60, 4, EMO_VOID), \
W("chancellery",     0.55, 4, EMO_VOID), \
W("surveillance",    0.65, 3, EMO_TRAUMA), \
W("fortification",   0.60, 5, EMO_VOID), \
W("colonnade",       0.60, 3, EMO_VOID), \
W("parapet",         0.50, 3, EMO_VOID), \
W("granite",         0.55, 2, EMO_VOID), \
W("plaster",         0.40, 2, EMO_VOID), \
W("stucco",          0.40, 2, EMO_VOID), \
W("gutter",          0.45, 2, EMO_VOID), \
W("drainpipe",       0.40, 2, EMO_VOID), \
/* === ABSTRACT HEAVY === */ \
W("predicament",     0.55, 4, EMO_JULIA), \
W("constellation",   0.65, 4, EMO_RESONANCE), \
W("thermodynamics",  0.60, 5, EMO_RESONANCE), \
W("deterioration",   0.65, 6, EMO_TRAUMA), \
W("hallucination",   0.60, 5, EMO_TRAUMA), \
W("hemorrhage",      0.70, 3, EMO_TRAUMA), \
W("surveillance",    0.55, 3, EMO_TRAUMA), \
W("bibliography",    0.45, 6, EMO_VOID), \
W("archaeology",     0.50, 5, EMO_VOID), \
W("inconsolable",    0.75, 5, EMO_JULIA), \
W("melancholy",      0.70, 4, EMO_JULIA), \
W("indifference",    0.60, 4, EMO_VOID), \
W("obsolescence",    0.55, 4, EMO_VOID), \
W("abandonment",     0.65, 4, EMO_JULIA), \
W("annihilation",    0.80, 5, EMO_TRAUMA), \
W("disintegration",  0.70, 5, EMO_TRAUMA), \
W("petrification",   0.65, 5, EMO_VOID), \
/* === NATURE — sparse, hard === */ \
W("permafrost",      0.55, 3, EMO_VOID), \
W("tundra",          0.50, 2, EMO_VOID), \
W("fjord",           0.45, 1, EMO_VOID), \
W("glacier",         0.55, 2, EMO_VOID), \
W("basalt",          0.50, 2, EMO_VOID), \
W("obsidian",        0.55, 4, EMO_VOID), \
W("sediment",        0.45, 3, EMO_VOID), \
W("limestone",       0.45, 2, EMO_VOID), \
W("erosion",         0.50, 3, EMO_VOID), \
W("estuary",         0.50, 4, EMO_RESONANCE), \
W("horizon",         0.55, 3, EMO_JULIA), \
W("equinox",         0.60, 3, EMO_RESONANCE), \
W("solstice",        0.60, 2, EMO_RESONANCE), \
/* === LIGHT WORDS — for contrast === */ \
W("dust",            0.30, 1, EMO_VOID), \
W("ink",             0.35, 1, EMO_VOID), \
W("salt",            0.30, 1, EMO_VOID), \
W("bone",            0.50, 1, EMO_TRAUMA), \
W("tin",             0.25, 1, EMO_VOID), \
W("ash",             0.40, 1, EMO_VOID), \
W("cod",             0.20, 1, EMO_VOID), \
W("elm",             0.25, 1, EMO_VOID), \
W("fog",             0.30, 1, EMO_VOID), \
W("birch",           0.35, 1, EMO_JULIA), \
W("moss",            0.25, 1, EMO_VOID), \
W("rust",            0.40, 1, EMO_VOID), \
W("soot",            0.35, 1, EMO_VOID), \
W("wax",             0.25, 1, EMO_VOID), \
W("chalk",           0.30, 1, EMO_VOID), \
W("wool",            0.25, 1, EMO_TENDERNESS), \
/* === TIME & AGING === */ \
W("chronometer",     0.55, 4, EMO_VOID), \
W("hourglass",       0.55, 2, EMO_VOID), \
W("antiquity",       0.60, 4, EMO_VOID), \
W("obsolete",        0.50, 3, EMO_VOID), \
W("calendar",        0.45, 3, EMO_VOID), \
W("epoch",           0.55, 2, EMO_VOID), \
W("millennium",      0.60, 4, EMO_VOID), \
W("aftermath",       0.55, 3, EMO_TRAUMA), \
/* === WATER — Brodsky's Venice === */ \
W("lagoon",          0.50, 2, EMO_JULIA), \
W("canal",           0.45, 2, EMO_JULIA), \
W("gondola",         0.50, 3, EMO_JULIA), \
W("watermark",       0.55, 3, EMO_JULIA), \
W("acqua",           0.45, 2, EMO_JULIA), \
W("tide",            0.40, 1, EMO_RESONANCE), \
W("current",         0.40, 2, EMO_RESONANCE), \
W("undertow",        0.55, 3, EMO_TRAUMA), \
W("tributary",       0.50, 4, EMO_RESONANCE), \
/* === EXILE — central Brodsky theme === */ \
W("exile",           0.80, 2, EMO_JULIA), \
W("departure",       0.65, 3, EMO_JULIA), \
W("displacement",    0.60, 3, EMO_JULIA), \
W("immigration",     0.55, 4, EMO_JULIA), \
W("passport",        0.50, 2, EMO_JULIA), \
W("customs",         0.40, 2, EMO_JULIA), \
W("border",          0.55, 2, EMO_JULIA), \
W("checkpoint",      0.50, 2, EMO_TRAUMA), \
W("nowhere",         0.60, 2, EMO_VOID), \
W("elsewhere",       0.55, 2, EMO_JULIA), \
/* === LANGUAGE & WRITING === */ \
W("consonant",       0.50, 3, EMO_RESONANCE), \
W("vowel",           0.45, 2, EMO_RESONANCE), \
W("syllable",        0.50, 3, EMO_RESONANCE), \
W("parenthesis",     0.50, 4, EMO_VOID), \
W("semicolon",       0.45, 4, EMO_VOID), \
W("apostrophe",      0.50, 4, EMO_VOID), \
W("manuscript",      0.55, 3, EMO_JULIA), \
W("typewriter",      0.55, 3, EMO_JULIA), \
W("postscript",      0.45, 2, EMO_VOID), \
W("translation",     0.55, 3, EMO_JULIA), \
/* === DOMESTIC — Brodsky's rooms === */ \
W("ceiling",         0.40, 2, EMO_VOID), \
W("wallpaper",       0.35, 3, EMO_VOID), \
W("radiator",        0.40, 4, EMO_VOID), \
W("doorframe",       0.35, 2, EMO_VOID), \
W("windowsill",      0.40, 3, EMO_JULIA), \
W("floorboard",      0.35, 2, EMO_VOID), \
W("staircase",       0.45, 2, EMO_VOID), \
W("corridor",        0.45, 3, EMO_VOID), \
W("wardrobe",        0.35, 2, EMO_VOID), \
W("mattress",        0.30, 2, EMO_VOID), \
/* === MISC HEAVY === */ \
W("government",      0.55, 3, EMO_VOID), \
W("population",      0.50, 4, EMO_VOID), \
W("photograph",      0.50, 3, EMO_JULIA), \
W("cigarette",       0.40, 3, EMO_VOID), \
W("telephone",       0.40, 3, EMO_JULIA), \
W("locomotive",      0.55, 4, EMO_VOID), \
W("mercury",         0.55, 4, EMO_RESONANCE), \
W("barometer",       0.50, 4, EMO_RESONANCE), \
W("oxygen",          0.45, 3, EMO_RESONANCE), \
W("hydrogen",        0.45, 3, EMO_RESONANCE), \
W("nitrogen",        0.40, 3, EMO_VOID), \
W("calcium",         0.40, 3, EMO_VOID), \
/* === FUNCTION WORDS — minimal, for glue === */ \
W("the",             0.05, 1, EMO_VOID), \
W("of",              0.05, 1, EMO_VOID), \
W("and",             0.05, 1, EMO_VOID), \
W("in",              0.05, 1, EMO_VOID), \
W("a",               0.05, 1, EMO_VOID), \
W("to",              0.05, 1, EMO_VOID), \
W("is",              0.05, 1, EMO_VOID), \
W("that",            0.10, 1, EMO_VOID), \
W("which",           0.10, 1, EMO_VOID), \
W("where",           0.15, 1, EMO_VOID), \
W("when",            0.10, 1, EMO_VOID), \
W("not",             0.20, 1, EMO_VOID), \
W("nor",             0.25, 1, EMO_VOID), \
W("neither",         0.30, 2, EMO_VOID), \
W("without",         0.30, 2, EMO_VOID), \
W("beneath",         0.30, 2, EMO_VOID), \
W("against",         0.30, 2, EMO_VOID), \
W("beyond",          0.35, 2, EMO_JULIA), \
W("among",           0.25, 2, EMO_VOID), \
W("between",         0.30, 2, EMO_VOID), \
W("toward",          0.25, 2, EMO_JULIA), \
W("through",         0.25, 1, EMO_VOID), \
W("across",          0.30, 2, EMO_JULIA), \
W("above",           0.25, 2, EMO_VOID), \
W("below",           0.25, 2, EMO_VOID), \
W("nothing",         0.50, 2, EMO_VOID), \
W("nobody",          0.50, 3, EMO_VOID), \
W("everywhere",      0.40, 3, EMO_VOID), \
W("somewhere",       0.35, 2, EMO_JULIA), \
W("perhaps",         0.30, 2, EMO_VOID), \
W("always",          0.35, 2, EMO_VOID), \
W("never",           0.45, 2, EMO_VOID), \
W("once",            0.30, 1, EMO_JULIA), \
W("still",           0.35, 1, EMO_VOID), \
W("yet",             0.30, 1, EMO_VOID), \
W("already",         0.30, 3, EMO_VOID), \
/* === VERBS — heavy, mechanical === */ \
W("calcify",         0.55, 3, EMO_VOID), \
W("deteriorate",     0.60, 4, EMO_TRAUMA), \
W("disintegrate",    0.65, 4, EMO_TRAUMA), \
W("petrify",         0.60, 3, EMO_VOID), \
W("corrode",         0.55, 2, EMO_TRAUMA), \
W("erode",           0.50, 2, EMO_VOID), \
W("ossify",          0.55, 3, EMO_VOID), \
W("congeal",         0.50, 2, EMO_VOID), \
W("crystallize",     0.55, 3, EMO_RESONANCE), \
W("evaporate",       0.50, 4, EMO_VOID), \
W("accumulate",      0.50, 4, EMO_VOID), \
W("accelerate",      0.50, 4, EMO_RESONANCE), \
W("reverberate",     0.55, 4, EMO_RESONANCE), \
W("disembark",       0.50, 3, EMO_JULIA), \
W("navigate",        0.45, 3, EMO_RESONANCE), \
W("approximate",     0.45, 4, EMO_RESONANCE), \
W("remember",        0.50, 3, EMO_JULIA), \
W("forget",          0.50, 2, EMO_VOID), \
W("abandon",         0.60, 3, EMO_JULIA), \
W("surrender",       0.55, 3, EMO_VOID), \
W("resemble",        0.40, 3, EMO_RESONANCE), \
W("diminish",        0.50, 3, EMO_VOID), \
W("extinguish",      0.55, 3, EMO_VOID), \
W("inhabit",         0.45, 3, EMO_JULIA), \
W("penetrate",       0.50, 3, EMO_TRAUMA), \
W("illuminate",      0.50, 4, EMO_RESONANCE), \
W("obliterate",      0.65, 4, EMO_TRAUMA), \
/* END */
