/* inhale/fr.h — French heavy vocabulary for brodsky.c
 * ~550 words. Baudelaire + Rimbaud + Apollinaire + Brodsky francophone register.
 * French syllable counting: pronounced vowel sounds.
 * Silent final -e doesn't count (usually). Nasals = 1 syllable.
 * Each word: text, mass, syllables, emotion
 */

/* W(word, mass, syllables, emotion) */
#define INHALE_FR \
/* === ÉTERNITÉS LOURDES === */ \
W("mort",             0.95, 1, EMO_TRAUMA), \
W("empire",           0.90, 2, EMO_VOID), \
W("éternité",         0.85, 4, EMO_RESONANCE), \
W("infini",           0.80, 3, EMO_RESONANCE), \
W("existence",        0.75, 3, EMO_VOID), \
W("espace",           0.75, 2, EMO_RESONANCE), \
W("temps",            0.80, 1, EMO_RESONANCE), \
W("néant",            0.90, 2, EMO_VOID), \
W("vide",             0.80, 1, EMO_VOID), \
W("absence",          0.75, 2, EMO_VOID), \
W("oubli",            0.70, 2, EMO_VOID), \
W("solitude",         0.80, 3, EMO_JULIA), \
W("abîme",            0.80, 2, EMO_VOID), \
/* === EXIL === */ \
W("exil",             0.90, 2, EMO_JULIA), \
W("bannissement",     0.80, 3, EMO_JULIA), \
W("séparation",       0.75, 4, EMO_JULIA), \
W("départ",           0.65, 2, EMO_JULIA), \
W("province",         0.60, 2, EMO_JULIA), \
W("patrie",           0.70, 2, EMO_JULIA), \
W("étranger",         0.65, 3, EMO_JULIA), \
W("frontière",        0.60, 2, EMO_JULIA), \
W("hémisphère",       0.55, 3, EMO_VOID), \
W("appartenance",     0.60, 3, EMO_JULIA), \
W("indifférence",     0.65, 4, EMO_VOID), \
W("déracinement",     0.70, 4, EMO_JULIA), \
W("nostalgie",        0.70, 4, EMO_JULIA), \
W("errance",          0.55, 2, EMO_JULIA), \
W("asile",            0.50, 2, EMO_JULIA), \
W("expatriation",     0.60, 5, EMO_JULIA), \
/* === ARCHITECTURE & EMPIRE === */ \
W("architecture",     0.70, 4, EMO_RESONANCE), \
W("colonnade",        0.65, 3, EMO_VOID), \
W("balustrade",       0.60, 3, EMO_VOID), \
W("quai",             0.50, 1, EMO_JULIA), \
W("façade",           0.55, 2, EMO_VOID), \
W("corniche",         0.50, 2, EMO_VOID), \
W("portique",         0.55, 2, EMO_VOID), \
W("cathédrale",       0.70, 3, EMO_VOID), \
W("aqueduc",          0.55, 3, EMO_VOID), \
W("amphithéâtre",     0.60, 4, EMO_VOID), \
W("crépi",            0.40, 2, EMO_VOID), \
W("granit",           0.55, 2, EMO_VOID), \
W("marbre",           0.60, 1, EMO_VOID), \
W("parapet",          0.50, 3, EMO_VOID), \
W("péristyle",        0.60, 3, EMO_VOID), \
W("colonne",          0.55, 2, EMO_VOID), \
W("pilastre",         0.50, 2, EMO_VOID), \
W("voûte",            0.55, 1, EMO_VOID), \
W("bureaucratie",     0.55, 4, EMO_VOID), \
W("forteresse",       0.60, 3, EMO_VOID), \
W("linteau",          0.50, 2, EMO_VOID), \
W("parvis",           0.50, 2, EMO_VOID), \
W("narthex",          0.55, 2, EMO_VOID), \
W("transept",         0.55, 2, EMO_VOID), \
W("abside",           0.50, 2, EMO_VOID), \
W("cloître",          0.50, 1, EMO_VOID), \
W("flèche",           0.45, 1, EMO_VOID), \
W("contrefort",       0.55, 2, EMO_VOID), \
W("crypte",           0.55, 1, EMO_VOID), \
W("ogive",            0.50, 2, EMO_VOID), \
W("rosace",           0.45, 2, EMO_RESONANCE), \
W("beffroi",          0.50, 2, EMO_VOID), \
W("donjon",           0.55, 2, EMO_VOID), \
W("citerne",          0.45, 2, EMO_VOID), \
/* === GÉOGRAPHIE === */ \
W("latitude",         0.55, 3, EMO_RESONANCE), \
W("longitude",        0.55, 3, EMO_RESONANCE), \
W("méridien",         0.60, 3, EMO_RESONANCE), \
W("presqu'île",       0.55, 2, EMO_JULIA), \
W("archipel",         0.55, 3, EMO_RESONANCE), \
W("détroit",          0.45, 2, EMO_VOID), \
W("continent",        0.55, 3, EMO_VOID), \
W("toundra",          0.50, 2, EMO_VOID), \
W("horizon",          0.55, 3, EMO_JULIA), \
W("désert",           0.55, 2, EMO_VOID), \
W("steppe",           0.50, 1, EMO_VOID), \
W("marécage",         0.45, 3, EMO_VOID), \
W("falaise",          0.50, 2, EMO_TRAUMA), \
W("isthme",           0.50, 1, EMO_VOID), \
W("promontoire",      0.55, 3, EMO_RESONANCE), \
/* === GÉOMÉTRIE === */ \
W("perpendiculaire",  0.65, 5, EMO_RESONANCE), \
W("tangente",         0.50, 2, EMO_RESONANCE), \
W("parabole",         0.55, 3, EMO_RESONANCE), \
W("hyperbole",        0.55, 3, EMO_RESONANCE), \
W("asymptote",        0.60, 3, EMO_JULIA), \
W("diagonale",        0.50, 4, EMO_RESONANCE), \
W("parallèle",        0.55, 3, EMO_RESONANCE), \
W("circonférence",    0.60, 4, EMO_RESONANCE), \
W("vecteur",          0.50, 2, EMO_RESONANCE), \
/* === CORPS — grotesque === */ \
W("vertèbre",         0.70, 2, EMO_TRAUMA), \
W("cartilage",        0.60, 3, EMO_TRAUMA), \
W("tendon",           0.55, 2, EMO_TRAUMA), \
W("sternum",          0.60, 2, EMO_TRAUMA), \
W("larynx",           0.60, 2, EMO_TRAUMA), \
W("diaphragme",       0.55, 3, EMO_TRAUMA), \
W("clavicule",        0.55, 3, EMO_TRAUMA), \
W("crâne",            0.65, 1, EMO_TRAUMA), \
W("squelette",        0.60, 2, EMO_TRAUMA), \
W("rétine",           0.50, 2, EMO_TRAUMA), \
W("pupille",          0.45, 2, EMO_TRAUMA), \
W("côte",             0.50, 1, EMO_TRAUMA), \
W("ossement",         0.55, 2, EMO_TRAUMA), \
W("chair",            0.55, 1, EMO_TRAUMA), \
W("sang",             0.60, 1, EMO_TRAUMA), \
W("fémur",            0.60, 2, EMO_TRAUMA), \
W("rotule",           0.50, 2, EMO_TRAUMA), \
W("trachée",          0.55, 2, EMO_TRAUMA), \
W("aorte",            0.65, 2, EMO_TRAUMA), \
W("bassin",           0.50, 2, EMO_TRAUMA), \
W("synapse",          0.55, 2, EMO_RESONANCE), \
W("omoplate",         0.55, 3, EMO_TRAUMA), \
W("phalange",         0.50, 2, EMO_TRAUMA), \
W("oesophage",        0.55, 3, EMO_TRAUMA), \
W("thyroïde",         0.50, 3, EMO_TRAUMA), \
W("moelle",           0.60, 1, EMO_TRAUMA), \
W("membrane",         0.50, 2, EMO_TRAUMA), \
W("vaisseau",         0.55, 2, EMO_TRAUMA), \
W("artère",           0.55, 2, EMO_TRAUMA), \
W("nerf",             0.50, 1, EMO_TRAUMA), \
W("peau",             0.40, 1, EMO_TENDERNESS), \
/* === EAU — Venise === */ \
W("lagune",           0.55, 2, EMO_JULIA), \
W("canal",            0.45, 2, EMO_JULIA), \
W("gondole",          0.50, 2, EMO_JULIA), \
W("embarcadère",      0.55, 4, EMO_JULIA), \
W("marée",            0.40, 2, EMO_RESONANCE), \
W("courant",          0.40, 2, EMO_RESONANCE), \
W("ressac",           0.50, 2, EMO_TRAUMA), \
W("affluent",         0.45, 3, EMO_RESONANCE), \
W("inondation",       0.55, 4, EMO_TRAUMA), \
W("estuaire",         0.50, 3, EMO_RESONANCE), \
W("embruns",          0.40, 2, EMO_JULIA), \
W("maelström",        0.65, 2, EMO_TRAUMA), \
W("naufrage",         0.65, 2, EMO_TRAUMA), \
W("abysses",          0.70, 2, EMO_VOID), \
W("houle",            0.45, 1, EMO_RESONANCE), \
/* === TEMPS & VIEILLISSEMENT === */ \
W("chronomètre",      0.55, 3, EMO_VOID), \
W("sablier",          0.50, 3, EMO_VOID), \
W("antiquité",        0.60, 4, EMO_VOID), \
W("millénaire",       0.60, 4, EMO_VOID), \
W("calendrier",       0.45, 3, EMO_VOID), \
W("époque",           0.55, 2, EMO_VOID), \
W("crépuscule",       0.55, 3, EMO_JULIA), \
W("aube",             0.40, 1, EMO_RESONANCE), \
W("minuit",           0.50, 2, EMO_VOID), \
W("équinoxe",         0.55, 3, EMO_RESONANCE), \
W("solstice",         0.55, 2, EMO_RESONANCE), \
W("immobilité",       0.60, 5, EMO_VOID), \
W("cadran",           0.45, 2, EMO_VOID), \
W("pendule",          0.45, 2, EMO_VOID), \
W("siècle",           0.60, 1, EMO_VOID), \
W("déclin",           0.55, 2, EMO_VOID), \
W("révolu",           0.50, 3, EMO_VOID), \
W("sursis",           0.50, 2, EMO_VOID), \
/* === ABSTRAITS LOURDS === */ \
W("civilisation",     0.65, 5, EMO_VOID), \
W("métamorphose",     0.70, 4, EMO_RESONANCE), \
W("destruction",      0.70, 3, EMO_TRAUMA), \
W("anéantissement",   0.80, 5, EMO_TRAUMA), \
W("pétrification",    0.60, 5, EMO_VOID), \
W("désintégration",   0.65, 5, EMO_TRAUMA), \
W("mélancolie",       0.70, 4, EMO_JULIA), \
W("hallucination",    0.55, 5, EMO_TRAUMA), \
W("hémorragie",       0.65, 4, EMO_TRAUMA), \
W("désolation",       0.65, 4, EMO_VOID), \
W("obsolescence",     0.55, 3, EMO_VOID), \
W("détérioration",    0.60, 5, EMO_TRAUMA), \
W("désespoir",        0.75, 3, EMO_TRAUMA), \
W("abandon",          0.65, 3, EMO_JULIA), \
W("gratitude",        0.50, 3, EMO_TENDERNESS), \
W("décomposition",    0.60, 5, EMO_TRAUMA), \
W("putréfaction",     0.65, 4, EMO_TRAUMA), \
W("gangrène",         0.70, 2, EMO_TRAUMA), \
W("remords",          0.60, 2, EMO_GRIEF), \
W("repentir",         0.55, 3, EMO_GRIEF), \
W("stupeur",          0.55, 2, EMO_TRAUMA), \
W("volupté",          0.60, 3, EMO_DESIRE), \
W("spleen",           0.75, 1, EMO_VOID), \
W("extase",           0.55, 2, EMO_RESONANCE), \
W("vertige",          0.60, 2, EMO_TRAUMA), \
W("torpeur",          0.55, 2, EMO_VOID), \
W("agonie",           0.75, 3, EMO_TRAUMA), \
W("délire",           0.55, 2, EMO_TRAUMA), \
W("ivresse",          0.50, 2, EMO_DESIRE), \
W("lucidité",         0.55, 4, EMO_RESONANCE), \
/* === BAUDELAIRE — FLEURS DU MAL === */ \
W("charogne",         0.80, 2, EMO_TRAUMA), \
W("gouffre",          0.75, 1, EMO_VOID), \
W("miasme",           0.55, 2, EMO_TRAUMA), \
W("vermine",          0.55, 2, EMO_TRAUMA), \
W("opium",            0.50, 2, EMO_DESIRE), \
W("encensoir",        0.45, 3, EMO_RESONANCE), \
W("sarcophage",       0.65, 3, EMO_VOID), \
W("linceul",          0.65, 2, EMO_TRAUMA), \
W("catafalque",       0.60, 3, EMO_VOID), \
W("supplice",         0.65, 2, EMO_TRAUMA), \
W("blasphème",        0.60, 2, EMO_RAGE), \
W("neige",            0.35, 1, EMO_JULIA), \
/* === RIMBAUD — ILLUMINATIONS === */ \
W("aurore",           0.45, 2, EMO_RESONANCE), \
W("déluge",           0.70, 2, EMO_TRAUMA), \
W("voyant",           0.55, 2, EMO_RESONANCE), \
W("alchimie",         0.60, 3, EMO_RESONANCE), \
W("damnation",        0.70, 3, EMO_TRAUMA), \
W("enfer",            0.80, 2, EMO_TRAUMA), \
W("saison",           0.40, 2, EMO_JULIA), \
W("dérèglement",      0.55, 3, EMO_RESONANCE), \
W("phosphore",        0.50, 2, EMO_RESONANCE), \
/* === LANGUE & ÉCRITURE === */ \
W("consonne",         0.50, 2, EMO_RESONANCE), \
W("voyelle",          0.45, 2, EMO_RESONANCE), \
W("syllabe",          0.50, 2, EMO_RESONANCE), \
W("strophe",          0.55, 1, EMO_RESONANCE), \
W("rime",             0.50, 1, EMO_RESONANCE), \
W("manuscrit",        0.55, 3, EMO_JULIA), \
W("traduction",       0.50, 3, EMO_JULIA), \
W("encre",            0.45, 1, EMO_VOID), \
W("alphabet",         0.45, 3, EMO_RESONANCE), \
W("grammaire",        0.50, 2, EMO_RESONANCE), \
W("syntaxe",          0.55, 2, EMO_RESONANCE), \
W("parenthèse",       0.45, 3, EMO_VOID), \
W("palimpseste",      0.60, 3, EMO_RESONANCE), \
W("alexandrin",       0.55, 4, EMO_RESONANCE), \
W("césure",           0.50, 2, EMO_RESONANCE), \
W("élégie",           0.55, 3, EMO_GRIEF), \
W("hémistiche",       0.50, 3, EMO_RESONANCE), \
W("épitaphe",         0.60, 3, EMO_VOID), \
/* === DOMESTIQUE === */ \
W("plafond",          0.40, 2, EMO_VOID), \
W("rebord",           0.35, 2, EMO_JULIA), \
W("radiateur",        0.35, 3, EMO_VOID), \
W("couloir",          0.45, 2, EMO_VOID), \
W("lampe",            0.30, 1, EMO_VOID), \
W("plancher",         0.35, 2, EMO_VOID), \
W("armoire",          0.35, 2, EMO_VOID), \
W("matelas",          0.30, 3, EMO_VOID), \
W("miroir",           0.50, 2, EMO_RESONANCE), \
W("escalier",         0.45, 3, EMO_VOID), \
W("seuil",            0.50, 1, EMO_JULIA), \
W("rideau",           0.35, 2, EMO_VOID), \
W("bouilloire",       0.30, 2, EMO_VOID), \
W("cendrier",         0.40, 2, EMO_VOID), \
W("étagère",          0.35, 3, EMO_VOID), \
W("abat-jour",        0.35, 2, EMO_VOID), \
W("linoléum",         0.35, 4, EMO_VOID), \
W("robinet",          0.30, 3, EMO_VOID), \
W("papier peint",     0.30, 3, EMO_VOID), \
W("serrure",          0.40, 2, EMO_VOID), \
W("tabouret",         0.30, 3, EMO_VOID), \
W("commode",          0.35, 2, EMO_VOID), \
W("volet",            0.35, 2, EMO_VOID), \
W("poignée",          0.30, 2, EMO_VOID), \
W("sonnette",         0.30, 2, EMO_VOID), \
/* === NATURE — dure, éparse === */ \
W("calcaire",         0.50, 2, EMO_VOID), \
W("basalte",          0.50, 2, EMO_VOID), \
W("obsidienne",       0.50, 3, EMO_VOID), \
W("glacier",          0.50, 2, EMO_VOID), \
W("sédiment",         0.45, 3, EMO_VOID), \
W("érosion",          0.50, 3, EMO_VOID), \
W("brouillard",       0.40, 2, EMO_VOID), \
W("mousse",           0.25, 1, EMO_VOID), \
W("bouleau",          0.35, 2, EMO_JULIA), \
W("lichen",           0.30, 2, EMO_VOID), \
W("tourbe",           0.40, 1, EMO_VOID), \
W("silex",            0.50, 2, EMO_VOID), \
W("givre",            0.40, 1, EMO_VOID), \
W("verglas",          0.45, 2, EMO_VOID), \
W("fondrière",        0.45, 2, EMO_VOID), \
W("maremme",          0.45, 2, EMO_VOID), \
W("gneiss",           0.50, 1, EMO_VOID), \
W("schiste",          0.50, 1, EMO_VOID), \
/* === MOTS LÉGERS — pour contraste === */ \
W("poussière",        0.35, 2, EMO_VOID), \
W("sel",              0.30, 1, EMO_VOID), \
W("os",               0.55, 1, EMO_TRAUMA), \
W("cendre",           0.45, 1, EMO_VOID), \
W("rouille",          0.40, 1, EMO_VOID), \
W("suie",             0.35, 1, EMO_VOID), \
W("cire",             0.30, 1, EMO_VOID), \
W("craie",            0.30, 1, EMO_VOID), \
W("étain",            0.30, 2, EMO_VOID), \
W("sciure",           0.25, 1, EMO_VOID), \
W("plâtre",           0.35, 1, EMO_VOID), \
W("moisissure",       0.40, 3, EMO_VOID), \
W("limaille",         0.35, 2, EMO_VOID), \
/* === VERBES — lourds, mécaniques === */ \
W("calcifier",        0.55, 4, EMO_VOID), \
W("détériorer",       0.60, 4, EMO_TRAUMA), \
W("désintégrer",      0.65, 4, EMO_TRAUMA), \
W("pétrifier",        0.55, 4, EMO_VOID), \
W("corroder",         0.55, 3, EMO_TRAUMA), \
W("éroder",           0.50, 3, EMO_VOID), \
W("cristalliser",     0.55, 4, EMO_RESONANCE), \
W("évaporer",         0.45, 4, EMO_VOID), \
W("accumuler",        0.45, 4, EMO_VOID), \
W("se souvenir",      0.55, 4, EMO_JULIA), \
W("oublier",          0.55, 3, EMO_VOID), \
W("abandonner",       0.60, 4, EMO_JULIA), \
W("habiter",          0.45, 3, EMO_JULIA), \
W("éteindre",         0.50, 2, EMO_VOID), \
W("contempler",       0.45, 3, EMO_RESONANCE), \
W("figer",            0.50, 2, EMO_VOID), \
W("anéantir",         0.70, 4, EMO_TRAUMA), \
W("décomposer",       0.55, 4, EMO_TRAUMA), \
W("s'évaporer",       0.50, 4, EMO_VOID), \
W("réverbérer",       0.55, 4, EMO_RESONANCE), \
W("s'accumuler",      0.50, 4, EMO_VOID), \
W("suinter",          0.45, 2, EMO_VOID), \
W("ronger",           0.55, 2, EMO_TRAUMA), \
W("suppurer",         0.50, 3, EMO_TRAUMA), \
W("enfouir",          0.50, 3, EMO_VOID), \
W("ensevelir",        0.55, 4, EMO_VOID), \
W("chanceler",        0.45, 3, EMO_TRAUMA), \
W("vaciller",         0.45, 3, EMO_TRAUMA), \
W("se dissoudre",     0.55, 3, EMO_VOID), \
W("tressaillir",      0.50, 3, EMO_TRAUMA), \
W("exhaler",          0.45, 3, EMO_VOID), \
W("ruisseler",        0.40, 3, EMO_RESONANCE), \
W("scintiller",       0.40, 3, EMO_RESONANCE), \
W("suffoquer",        0.60, 3, EMO_TRAUMA), \
W("croupir",          0.50, 2, EMO_VOID), \
/* === SENSATIONS & DÉSIR === */ \
W("frisson",          0.45, 2, EMO_DESIRE), \
W("caresse",          0.40, 2, EMO_TENDERNESS), \
W("fièvre",           0.55, 1, EMO_DESIRE), \
W("brûlure",          0.55, 2, EMO_TRAUMA), \
W("sueur",            0.40, 2, EMO_TRAUMA), \
W("cicatrice",        0.55, 3, EMO_TRAUMA), \
W("frémissement",     0.45, 3, EMO_DESIRE), \
W("parfum",           0.40, 2, EMO_DESIRE), \
W("nausée",           0.55, 2, EMO_TRAUMA), \
W("soif",             0.50, 1, EMO_DESIRE), \
/* === DEUIL & GRIEF === */ \
W("tombeau",          0.70, 2, EMO_GRIEF), \
W("sépulcre",         0.70, 2, EMO_GRIEF), \
W("deuil",            0.75, 1, EMO_GRIEF), \
W("requiem",          0.65, 3, EMO_GRIEF), \
W("cortège",          0.55, 2, EMO_GRIEF), \
W("suaire",           0.60, 2, EMO_GRIEF), \
W("lamentation",      0.65, 4, EMO_GRIEF), \
W("veuve",            0.55, 1, EMO_GRIEF), \
W("chrysanthème",     0.50, 3, EMO_GRIEF), \
W("glas",             0.60, 1, EMO_GRIEF), \
/* === RAGE & VIOLENCE === */ \
W("fracas",           0.65, 2, EMO_RAGE), \
W("convulsion",       0.60, 3, EMO_RAGE), \
W("déflagration",     0.70, 4, EMO_RAGE), \
W("éclat",            0.55, 2, EMO_RAGE), \
W("hérésie",          0.55, 3, EMO_RAGE), \
W("insurrection",     0.65, 4, EMO_RAGE), \
W("cataclysme",       0.70, 3, EMO_RAGE), \
/* === SUBSTANCES & MATIÈRE === */ \
W("arsenic",          0.65, 3, EMO_TRAUMA), \
W("bitume",           0.50, 2, EMO_VOID), \
W("goudron",          0.50, 2, EMO_VOID), \
W("ammoniaque",       0.50, 3, EMO_TRAUMA), \
W("vitriol",          0.65, 3, EMO_RAGE), \
W("formol",           0.55, 2, EMO_VOID), \
W("camphre",          0.40, 1, EMO_VOID), \
W("naphtaline",       0.40, 3, EMO_VOID), \
W("soufre",           0.55, 1, EMO_TRAUMA), \
/* === JOIE & TENDRESSE — rare === */ \
W("berceau",          0.40, 2, EMO_TENDERNESS), \
W("clarté",           0.40, 2, EMO_JOY), \
W("murmure",          0.35, 2, EMO_TENDERNESS), \
W("tiède",            0.30, 1, EMO_TENDERNESS), \
W("berceuse",         0.35, 2, EMO_TENDERNESS), \
W("effleurer",        0.35, 3, EMO_TENDERNESS), \
W("lueur",            0.35, 2, EMO_JOY), \
/* === DIVERS LOURDS === */ \
W("gouvernement",     0.55, 3, EMO_VOID), \
W("population",       0.50, 4, EMO_VOID), \
W("photographie",     0.50, 4, EMO_JULIA), \
W("cigarette",        0.40, 3, EMO_VOID), \
W("locomotive",       0.55, 4, EMO_VOID), \
W("mercure",          0.55, 2, EMO_RESONANCE), \
W("baromètre",        0.50, 3, EMO_RESONANCE), \
W("oxygène",          0.45, 3, EMO_RESONANCE), \
W("téléphone",        0.40, 3, EMO_VOID), \
W("tramway",          0.40, 2, EMO_VOID), \
W("pendentif",        0.40, 3, EMO_JULIA), \
W("barbelure",        0.50, 3, EMO_TRAUMA), \
W("amiante",          0.50, 2, EMO_TRAUMA), \
W("horloge",          0.45, 2, EMO_VOID), \
/* === MOTS-OUTILS — seulement lourds === */ \
W("jamais",           0.50, 2, EMO_VOID), \
W("nulle part",       0.50, 2, EMO_VOID), \
W("rien",             0.55, 1, EMO_VOID), \
W("personne",         0.50, 2, EMO_VOID), \
W("malgré",           0.35, 2, EMO_VOID), \
W("parmi",            0.25, 2, EMO_VOID), \
W("entre",            0.25, 1, EMO_VOID), \
W("au-delà",          0.40, 3, EMO_JULIA), \
W("en dessous",       0.30, 3, EMO_VOID), \
W("à travers",        0.30, 3, EMO_VOID), \
W("partout",          0.35, 2, EMO_VOID), \
W("toujours",         0.40, 2, EMO_VOID), \
W("encore",           0.30, 2, EMO_VOID), \
W("déjà",             0.30, 2, EMO_VOID), \
W("peut-être",        0.30, 2, EMO_VOID), \
W("désormais",        0.40, 3, EMO_VOID), \
W("néanmoins",        0.35, 3, EMO_VOID), \
W("davantage",        0.30, 3, EMO_VOID), \
/* === NUIT & OMBRES === */ \
W("pénombre",         0.50, 2, EMO_VOID), \
W("ténèbres",         0.65, 2, EMO_VOID), \
W("nocturne",         0.50, 2, EMO_VOID), \
W("insomnie",         0.55, 3, EMO_JULIA), \
W("cauchemar",        0.60, 2, EMO_TRAUMA), \
/* === THÉOLOGIE NOIRE === */ \
W("purgatoire",       0.65, 3, EMO_VOID), \
W("pénitence",        0.55, 3, EMO_GRIEF), \
W("stigmate",         0.60, 2, EMO_TRAUMA), \
W("résurrection",     0.55, 4, EMO_RESONANCE), \
W("crucifix",         0.60, 3, EMO_TRAUMA), \
W("reliquaire",       0.50, 3, EMO_VOID), \
W("sacristie",        0.45, 3, EMO_VOID), \
W("prophétie",        0.55, 3, EMO_RESONANCE), \
/* === MODERNE / URBAIN — Apollinaire === */ \
W("métro",            0.45, 2, EMO_VOID), \
W("asphalte",         0.50, 2, EMO_VOID), \
W("néon",             0.40, 2, EMO_VOID), \
W("béton",            0.50, 2, EMO_VOID), \
W("antenne",          0.40, 2, EMO_VOID), \
W("trottoir",         0.40, 2, EMO_VOID), \
W("réverbère",        0.45, 3, EMO_VOID), \
W("caniveau",         0.40, 3, EMO_VOID), \
W("gouttière",        0.40, 2, EMO_VOID), \
W("chaussée",         0.35, 2, EMO_VOID), \
W("carrefour",        0.40, 2, EMO_VOID), \
W("enseigne",         0.35, 2, EMO_VOID), \
W("devanture",        0.35, 3, EMO_VOID), \
W("pylône",           0.45, 2, EMO_VOID), \
W("poutrelle",        0.40, 2, EMO_VOID), \
W("cheminée",         0.40, 3, EMO_VOID), \
W("grillage",         0.35, 2, EMO_VOID), \
W("passerelle",       0.40, 3, EMO_VOID), \
W("bouche d'égout",   0.45, 3, EMO_VOID), \
W("auvent",           0.30, 2, EMO_VOID), \
W("chantier",         0.40, 2, EMO_VOID), \
W("hangar",           0.40, 2, EMO_VOID), \
W("faubourg",         0.45, 2, EMO_JULIA), \
W("banlieue",         0.45, 2, EMO_JULIA), \
W("cour",             0.35, 1, EMO_VOID), \
W("impasse",          0.45, 2, EMO_VOID), \
W("palissade",        0.40, 3, EMO_VOID), \
/* === VERBES DE PERCEPTION === */ \
W("entrevoir",        0.45, 3, EMO_JULIA), \
W("tâtonner",         0.40, 3, EMO_VOID), \
W("trébucher",        0.45, 3, EMO_TRAUMA), \
W("balbutier",        0.45, 4, EMO_TRAUMA), \
W("frissonner",       0.45, 3, EMO_DESIRE), \
W("cligner",          0.35, 2, EMO_VOID), \
W("murmurer",         0.40, 3, EMO_TENDERNESS), \
W("humer",            0.30, 2, EMO_DESIRE), \
W("palper",           0.40, 2, EMO_TRAUMA), \
W("scruter",          0.45, 2, EMO_VOID), \
W("pressentir",       0.50, 3, EMO_JULIA), \
W("deviner",          0.40, 3, EMO_RESONANCE), \
W("percevoir",        0.45, 3, EMO_RESONANCE), \
W("discerner",        0.45, 3, EMO_RESONANCE), \
W("guetter",          0.45, 2, EMO_VOID), \
W("épier",            0.40, 3, EMO_VOID), \
W("affleurer",        0.35, 3, EMO_TENDERNESS), \
/* === NOURRITURE === */ \
W("café",             0.30, 2, EMO_VOID), \
W("vodka",            0.40, 2, EMO_VOID), \
W("hareng",           0.35, 2, EMO_VOID), \
W("pain",             0.25, 1, EMO_TENDERNESS), \
W("vinaigre",         0.35, 2, EMO_VOID), \
W("moutarde",         0.30, 2, EMO_VOID), \
W("poivre",           0.30, 1, EMO_VOID), \
W("absinthe",         0.50, 2, EMO_DESIRE), \
W("croûte",           0.30, 1, EMO_VOID), \
W("saumure",          0.35, 2, EMO_VOID), \
W("levain",           0.30, 2, EMO_VOID), \
W("lie",              0.35, 1, EMO_VOID), \
W("marc",             0.30, 1, EMO_VOID), \
W("viande",           0.35, 1, EMO_TRAUMA), \
/* === VÊTEMENTS === */ \
W("pardessus",        0.40, 3, EMO_JULIA), \
W("galoche",          0.35, 2, EMO_VOID), \
W("revers",           0.35, 2, EMO_VOID), \
W("col",              0.30, 1, EMO_VOID), \
W("boutonnière",      0.35, 3, EMO_VOID), \
W("capote",           0.35, 2, EMO_VOID), \
W("écharpe",          0.30, 2, EMO_JULIA), \
W("semelle",          0.30, 2, EMO_VOID), \
W("doublure",         0.30, 2, EMO_VOID), \
W("ourlet",           0.30, 2, EMO_VOID), \
W("feutre",           0.35, 1, EMO_VOID), \
W("bretelle",         0.30, 2, EMO_VOID), \
W("guenille",         0.40, 2, EMO_TRAUMA), \
/* === VERBES MÉDICAUX === */ \
W("amputer",          0.65, 3, EMO_TRAUMA), \
W("diagnostiquer",    0.55, 4, EMO_VOID), \
W("suturer",          0.55, 3, EMO_TRAUMA), \
W("anesthésier",      0.50, 4, EMO_VOID), \
W("réanimer",         0.55, 4, EMO_RESONANCE), \
W("cautériser",       0.55, 4, EMO_TRAUMA), \
W("ausculter",        0.45, 3, EMO_VOID), \
W("inciser",          0.55, 3, EMO_TRAUMA), \
W("inoculer",         0.45, 4, EMO_VOID), \
W("disséquer",        0.55, 3, EMO_TRAUMA), \
W("panser",           0.40, 2, EMO_TENDERNESS), \
W("recoudre",         0.50, 2, EMO_TRAUMA), \
W("transfuser",       0.50, 3, EMO_TRAUMA), \
/* === APOLLINAIRE — ZONE / CALLIGRAMMES === */ \
W("zone",             0.55, 1, EMO_VOID), \
W("pont",             0.40, 1, EMO_JULIA), \
W("tour",             0.45, 1, EMO_VOID), \
W("fleuve",           0.45, 1, EMO_RESONANCE), \
W("berge",            0.35, 1, EMO_JULIA), \
W("gare",             0.40, 1, EMO_JULIA), \
W("autobus",          0.35, 3, EMO_VOID), \
W("piéton",           0.35, 2, EMO_VOID), \
W("passage",          0.35, 2, EMO_VOID), \
W("affiche",          0.30, 2, EMO_VOID), \
W("journal",          0.35, 2, EMO_VOID), \
W("vitrine",          0.35, 2, EMO_VOID), \
W("quincaillerie",    0.40, 4, EMO_VOID), \
W("sifflet",          0.35, 2, EMO_VOID), \
W("foule",            0.40, 1, EMO_VOID), \
W("aéroplane",        0.40, 3, EMO_RESONANCE), \
W("paquebot",         0.40, 3, EMO_JULIA), \
W("cheminot",         0.35, 3, EMO_VOID), \
W("usine",            0.45, 2, EMO_VOID), \
W("sirène",           0.45, 2, EMO_TRAUMA), \
/* === MONOSYLLABES DE CONTRASTE === */ \
W("fiel",             0.45, 1, EMO_RAGE), \
W("boue",             0.40, 1, EMO_VOID), \
W("crasse",           0.40, 1, EMO_VOID), \
W("laque",            0.30, 1, EMO_VOID), \
W("brai",             0.35, 1, EMO_VOID), \
W("chaux",            0.30, 1, EMO_VOID), \
W("zinc",             0.35, 1, EMO_VOID), \
W("plomb",            0.50, 1, EMO_VOID), \
W("fonte",            0.40, 1, EMO_VOID), \
W("glaise",           0.35, 1, EMO_VOID), \
W("scorie",           0.40, 2, EMO_VOID), \
W("mâche",            0.30, 1, EMO_VOID), \
W("tôle",             0.35, 1, EMO_VOID), \
/* === VERBES — urbains, cassés === */ \
W("arpenter",         0.40, 3, EMO_VOID), \
W("déraper",          0.45, 3, EMO_TRAUMA), \
W("grincer",          0.45, 2, EMO_TRAUMA), \
W("écraser",          0.50, 3, EMO_TRAUMA), \
W("éblouir",          0.40, 3, EMO_RESONANCE), \
W("claudiquer",       0.45, 3, EMO_TRAUMA), \
W("dégouliner",       0.40, 4, EMO_VOID), \
W("rôder",            0.40, 2, EMO_VOID), \
W("échouer",          0.50, 3, EMO_JULIA), \
W("disperser",        0.45, 3, EMO_VOID), \
W("tanguer",          0.40, 2, EMO_TRAUMA), \
W("défigurer",        0.55, 4, EMO_TRAUMA), \
W("calfeutrer",       0.40, 3, EMO_VOID), \
W("colmater",         0.40, 3, EMO_VOID), \
W("raccommodor",      0.40, 4, EMO_VOID), \
W("étayer",           0.35, 3, EMO_VOID), \
/* === ABSTRAITS — Apollinaire === */ \
W("modernité",        0.55, 4, EMO_VOID), \
W("simultanéité",     0.55, 6, EMO_RESONANCE), \
W("ubiquité",         0.50, 4, EMO_RESONANCE), \
W("vitesse",          0.45, 2, EMO_VOID), \
W("multitude",        0.50, 3, EMO_VOID), \
W("monotonie",        0.50, 4, EMO_VOID), \
W("anonymat",         0.50, 3, EMO_VOID), \
W("promiscuité",      0.50, 5, EMO_VOID), \
W("simulacre",        0.50, 3, EMO_VOID), \
W("verticalité",      0.50, 5, EMO_RESONANCE), \
W("précipice",        0.55, 3, EMO_TRAUMA), \
W("convoi",           0.40, 2, EMO_VOID), \
W("ferraille",        0.40, 2, EMO_VOID), \
W("gravats",          0.40, 2, EMO_VOID), \
W("friche",           0.35, 1, EMO_VOID), \
W("carcasse",         0.50, 2, EMO_TRAUMA), \
W("décombre",         0.50, 2, EMO_TRAUMA), \
W("cadastre",         0.40, 2, EMO_VOID), \
/* END */
